package org.cocktail.feve.components;
// Generated by the WOLips TemplateEngine Plug-in at 23 ao�t 2005 15:23:28

import org.cocktail.feve.components.common.FeveTopMenuPage;
import org.cocktail.feve.eos.modele.grhum.EOIndividu;

import com.webobjects.appserver.WOComponent;
import com.webobjects.appserver.WOContext;

public class PageChangeIdentite extends FeveTopMenuPage {

	public EOIndividu lIndividuSelectionne;
  
  public PageChangeIdentite(WOContext context) {
    super(context);
  }
  
  /**
   * connecte l'individu selectionne (CAS reste sur le login de l'ancienne personne)
   * @return
   */
  public WOComponent prendreIdentite() {
    if (lIndividuSelectionne != null) {
    	session.initSession();
      return session.loginRedirect(lIndividuSelectionne.persId());
    }
    return neFaitRien();
  }

}