package org.cocktail.feve.components;
// Generated by the WOLips TemplateEngine Plug-in at 18 mai 2005 10:43:51


import org.cocktail.feve.components.common.FeveTopMenuPage;

import com.webobjects.appserver.WOContext;


public class PageAccueil extends FeveTopMenuPage {

	public PageAccueil(WOContext context) {
		super(context);
	}
	
}