-- ajout de dates de validité des niveaux des compétences
ALTER TABLE GRHUM.NIVEAU_COMPETENCE_PRO ADD (D_DEB_VAL  DATE);
ALTER TABLE GRHUM.NIVEAU_COMPETENCE_PRO ADD (D_FIN_VAL  DATE);
ALTER TABLE GRHUM.NIVEAU_COMPETENCE_PRO ADD (NCP_POSITION	NUMBER);

COMMENT ON TABLE GRHUM.NIVEAU_COMPETENCE_PRO IS 'Niveaux des compétences professionnelles des fiches de postes affectés dans les entretiens professionels';
COMMENT ON COLUMN GRHUM.NIVEAU_COMPETENCE_PRO.NCP_KEY IS 'Clé primaire';
COMMENT ON COLUMN GRHUM.NIVEAU_COMPETENCE_PRO.NCP_LIBELLE IS 'Libellé du niveau de compétence';
COMMENT ON COLUMN GRHUM.NIVEAU_COMPETENCE_PRO.D_DEB_VAL IS 'Date de début de validité de l''occurrence';
COMMENT ON COLUMN GRHUM.NIVEAU_COMPETENCE_PRO.D_FIN_VAL IS 'Date de fin de validité de l''occurrence';
COMMENT ON COLUMN GRHUM.NIVEAU_COMPETENCE_PRO.NCP_POSITION IS 'L''ordre d''affichage de ce niveau parmi une liste';

-- archivage des anciens niveaux de compétence professionnel
UPDATE GRHUM.NIVEAU_COMPETENCE_PRO SET D_DEB_VAL = TO_DATE('01/09/2004', 'DD/MM/YYYY'), D_FIN_VAL = TO_DATE('31/08/2009', 'DD/MM/YYYY');

-- nouveaux niveaux
INSERT INTO GRHUM.NIVEAU_COMPETENCE_PRO ( NCP_KEY, NCP_LIBELLE, D_DEB_VAL, D_FIN_VAL , NCP_POSITION) VALUES (5, 'A améliorer',  TO_DATE( '01/09/2009', 'MM/DD/YYYY'), NULL, 3); 
INSERT INTO GRHUM.NIVEAU_COMPETENCE_PRO ( NCP_KEY, NCP_LIBELLE, D_DEB_VAL, D_FIN_VAL , NCP_POSITION) VALUES (6, 'En progrès',  TO_DATE( '01/09/2009', 'MM/DD/YYYY'), NULL, 2); 
INSERT INTO GRHUM.NIVEAU_COMPETENCE_PRO ( NCP_KEY, NCP_LIBELLE, D_DEB_VAL, D_FIN_VAL , NCP_POSITION) VALUES (7, 'Acquis',  TO_DATE( '01/09/2009', 'MM/DD/YYYY'), NULL, 1); 

