-- ajout de dates de validité des association des valeurs au items pour les templates
ALTER TABLE MANGUE.TPL_REPART_ITEM_ITEM_VALEUR ADD (D_DEB_VAL  DATE);
ALTER TABLE MANGUE.TPL_REPART_ITEM_ITEM_VALEUR ADD (D_FIN_VAL  DATE);
ALTER TABLE MANGUE.TPL_REPART_ITEM_ITEM_VALEUR ADD (TIV_POSITION	NUMBER);

COMMENT ON COLUMN MANGUE.TPL_REPART_ITEM_ITEM_VALEUR.D_DEB_VAL IS 'Date de début de validité de l''occurrence';
COMMENT ON COLUMN MANGUE.TPL_REPART_ITEM_ITEM_VALEUR.D_FIN_VAL IS 'Date de fin de validité de l''occurrence';
COMMENT ON COLUMN MANGUE.TPL_REPART_ITEM_ITEM_VALEUR.D_FIN_VAL IS 'L''ordre d''affichage de la valeur parmi une liste';

-- nouveaux niveaux
INSERT INTO MANGUE.TPL_ITEM_VALEUR ( TIV_KEY, TIV_LIBELLE, TIV_COMMENTAIRE, D_CREATION, D_MODIFICATION ) VALUES (5, 'Acquis', NULL, SYSDATE, SYSDATE); 
INSERT INTO MANGUE.TPL_ITEM_VALEUR ( TIV_KEY, TIV_LIBELLE, TIV_COMMENTAIRE, D_CREATION, D_MODIFICATION ) VALUES (6, 'En progrès', NULL, SYSDATE, SYSDATE); 
INSERT INTO MANGUE.TPL_ITEM_VALEUR ( TIV_KEY, TIV_LIBELLE, TIV_COMMENTAIRE, D_CREATION, D_MODIFICATION ) VALUES (7, 'A améliorer', NULL, SYSDATE, SYSDATE); 

-- association des nouveaux niveaux / positions
INSERT INTO MANGUE.TPL_REPART_ITEM_ITEM_VALEUR( TIT_KEY, TIV_KEY, D_CREATION, D_MODIFICATION, D_DEB_VAL, D_FIN_VAL, TIV_POSITION) 
SELECT TIT_KEY, 5, SYSDATE, SYSDATE, TO_DATE( '01/09/2009', 'MM/DD/YYYY'), NULL, 1
FROM MANGUE.TPL_REPART_ITEM_ITEM_VALEUR
WHERE TIV_KEY = 1;

INSERT INTO MANGUE.TPL_REPART_ITEM_ITEM_VALEUR( TIT_KEY, TIV_KEY, D_CREATION, D_MODIFICATION, D_DEB_VAL, D_FIN_VAL, TIV_POSITION) 
SELECT TIT_KEY, 6, SYSDATE, SYSDATE, TO_DATE( '01/09/2009', 'MM/DD/YYYY'), NULL, 2
FROM MANGUE.TPL_REPART_ITEM_ITEM_VALEUR
WHERE TIV_KEY = 1;

INSERT INTO MANGUE.TPL_REPART_ITEM_ITEM_VALEUR( TIT_KEY, TIV_KEY, D_CREATION, D_MODIFICATION, D_DEB_VAL, D_FIN_VAL, TIV_POSITION) 
SELECT TIT_KEY, 7, SYSDATE, SYSDATE, TO_DATE( '01/09/2009', 'MM/DD/YYYY'), NULL, 3
FROM MANGUE.TPL_REPART_ITEM_ITEM_VALEUR
WHERE TIV_KEY = 1;

-- mise à jour des dates de validité et des positions
UPDATE MANGUE.TPL_REPART_ITEM_ITEM_VALEUR 
SET D_DEB_VAL = TO_DATE('01/09/2004', 'DD/MM/YYYY'), D_FIN_VAL = TO_DATE('31/08/2009', 'DD/MM/YYYY'), D_MODIFICATION = SYSDATE
WHERE TIV_KEY IN (1,2,3);

UPDATE MANGUE.TPL_REPART_ITEM_ITEM_VALEUR 
SET D_DEB_VAL = TO_DATE('01/09/2004', 'DD/MM/YYYY'), D_MODIFICATION = SYSDATE, TIV_POSITION = 4
WHERE TIV_KEY = 4;

UPDATE MANGUE.TPL_REPART_ITEM_ITEM_VALEUR 
SET D_DEB_VAL = TO_DATE('01/09/2009', 'DD/MM/YYYY'), D_MODIFICATION = SYSDATE
WHERE TIV_KEY IN (5,6,7);