package org.cocktail.feve.components.fichelolf;
// Generated by the WOLips TemplateEngine Plug-in at 16 nov. 2005 15:22:19

import org.cocktail.feve.components.common.A_FeveSubMenuPage;
import org.cocktail.feve.eos.modele.mangue.A_Fiche;
import org.cocktail.feve.eos.modele.mangue.EOAffectationDetail;
import org.cocktail.feve.eos.modele.mangue.EOFicheLolf;

import com.webobjects.appserver.WOContext;
import com.webobjects.foundation.NSArray;


public class PageFicheLolf extends A_FeveSubMenuPage {
  // variables entrantes
  private EOFicheLolf inputLaFicheLolf;
  private EOFicheLolf inputLaFicheLolfPrecedente;
  
  /**
   * On affiche une message d'entete pour chaque fiche
   * rappelant sur qui on travaille
   */
  public String enteteDetail;

  public PageFicheLolf(WOContext context) {
    super(context);
  }

  private final static String MENU_ITEM_AGENT 				= "Agent";
  private final static String MENU_ITEM_DESCRIPTION 	= "Description";
  
  // gestion du menu
     
  public NSArray getMenuItems() {
  	return new NSArray(new String[]{
  			MENU_ITEM_AGENT,MENU_ITEM_DESCRIPTION}); 
  }
 
  // setter
  
  /**
   * detection du changement du point d'entree -> RAZ
   */
  public void setInputLaFicheLolf(EOFicheLolf value) {
    inputLaFicheLolfPrecedente = inputLaFicheLolf;
    inputLaFicheLolf = value;
    if (inputLaFicheLolf != inputLaFicheLolfPrecedente) {
      setSelectedItemMenu(null);
    }
    // entete pour afficher sur qui on travaille
    EOAffectationDetail recAffectationDetail = ((A_Fiche)value).toAffectationDetailActuelle();
  	if (recAffectationDetail == null) {
  		recAffectationDetail = ((A_Fiche)value).toAffectationDetailDerniere();
  	}		
    enteteDetail = (recAffectationDetail!= null && recAffectationDetail.toAffectation() != null ?
    		recAffectationDetail.toAffectation().toIndividu().display() +" / ": 
    		"")+ value.valueForKey("display");
  }


  // getters

  public EOFicheLolf inputLaFicheLolf() { return inputLaFicheLolf; }
  
  // boolean interface 
  public boolean isPageFlo1()         {   return getSelectedItemMenu().equals(getMenuItems().objectAtIndex(0)); }
  public boolean isPageFlo2()         {   return getSelectedItemMenu().equals(getMenuItems().objectAtIndex(1)); }

}