SET DEFINE OFF;

--
-- FORMATION_PERSONNEL  (Table) 
--
CREATE TABLE GRHUM.FORMATION_PERSONNEL
(
  FOR_ID           NUMBER,
  FOR_LIBELLE      VARCHAR2(4000)               NOT NULL,
  FOR_COMMENTAIRE  VARCHAR2(4000),
  FOR_D_OUVERTURE  DATE,
  FOR_D_FERMETURE  DATE,
  D_CREATION       DATE                         DEFAULT SYSDATE               NOT NULL,
  D_MODIFICATION   DATE                         DEFAULT SYSDATE               NOT NULL,
  FOR_ID_PERE      NUMBER                       NOT NULL
)
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


-- 
-- Non Foreign Key Constraints for Table FORMATION_PERSONNEL 
-- 
ALTER TABLE GRHUM.FORMATION_PERSONNEL ADD (
  CONSTRAINT PK_FORMATION_PERSONNEL
 PRIMARY KEY
 (FOR_ID));

-- 
-- Foreign Key Constraints for Table FORMATION_PERSONNEL_OLD 
-- 
ALTER TABLE GRHUM.FORMATION_PERSONNEL ADD (
  CONSTRAINT FK_FORMATION_PERE 
 FOREIGN KEY (FOR_ID) 
 REFERENCES GRHUM.FORMATION_PERSONNEL (FOR_ID));


COMMENT ON TABLE GRHUM.FORMATION_PERSONNEL IS 'Nomenclature des formations locales de l''établissement';
COMMENT ON COLUMN GRHUM.FORMATION_PERSONNEL.FOR_ID IS 'Clé primaire';
COMMENT ON COLUMN GRHUM.FORMATION_PERSONNEL.FOR_LIBELLE IS 'Libellé de la formation';
COMMENT ON COLUMN GRHUM.FORMATION_PERSONNEL.FOR_COMMENTAIRE IS 'Commentaire';
COMMENT ON COLUMN GRHUM.FORMATION_PERSONNEL.FOR_D_OUVERTURE IS 'Date de début de validité';
COMMENT ON COLUMN GRHUM.FORMATION_PERSONNEL.FOR_D_FERMETURE IS 'Date de fin de validité';
COMMENT ON COLUMN GRHUM.FORMATION_PERSONNEL.D_CREATION IS 'Date de création de l''enregistrement';
COMMENT ON COLUMN GRHUM.FORMATION_PERSONNEL.D_MODIFICATION IS 'Date de dernière modification de l''enregistrement';
COMMENT ON COLUMN GRHUM.FORMATION_PERSONNEL.FOR_ID_PERE IS 'Formation père';


GRANT REFERENCES, SELECT ON GRHUM.FORMATION_PERSONNEL TO MANGUE;


Insert into GRHUM.FORMATION_PERSONNEL
   (FOR_ID, FOR_LIBELLE, FOR_COMMENTAIRE, FOR_D_OUVERTURE, FOR_D_FERMETURE, 
    D_CREATION, D_MODIFICATION, FOR_ID_PERE)
 Values
   (2, 'Patrimoine - logistique', NULL, NULL, NULL, SYSDATE, SYSDATE, 2);
Insert into GRHUM.FORMATION_PERSONNEL
   (FOR_ID, FOR_LIBELLE, FOR_COMMENTAIRE, FOR_D_OUVERTURE, FOR_D_FERMETURE, 
    D_CREATION, D_MODIFICATION, FOR_ID_PERE)
 Values
   (3, 'Gestion et pilotage', NULL, NULL, NULL, SYSDATE, SYSDATE, 3);
Insert into GRHUM.FORMATION_PERSONNEL
   (FOR_ID, FOR_LIBELLE, FOR_COMMENTAIRE, FOR_D_OUVERTURE, FOR_D_FERMETURE, 
    D_CREATION, D_MODIFICATION, FOR_ID_PERE)
 Values
   (4, 'Informatique - multimédia', NULL, NULL, NULL, SYSDATE, SYSDATE, 4);
Insert into GRHUM.FORMATION_PERSONNEL
   (FOR_ID, FOR_LIBELLE, FOR_COMMENTAIRE, FOR_D_OUVERTURE, FOR_D_FERMETURE, 
    D_CREATION, D_MODIFICATION, FOR_ID_PERE)
 Values
   (5, 'Documentation - Bibliothèques', NULL, NULL, NULL, SYSDATE, SYSDATE, 5);
Insert into GRHUM.FORMATION_PERSONNEL
   (FOR_ID, FOR_LIBELLE, FOR_COMMENTAIRE, FOR_D_OUVERTURE, FOR_D_FERMETURE, 
    D_CREATION, D_MODIFICATION, FOR_ID_PERE)
 Values
   (6, 'Promotion professionnelle', NULL, NULL, NULL, SYSDATE, SYSDATE, 6);
Insert into GRHUM.FORMATION_PERSONNEL
   (FOR_ID, FOR_LIBELLE, FOR_COMMENTAIRE, FOR_D_OUVERTURE, FOR_D_FERMETURE, 
    D_CREATION, D_MODIFICATION, FOR_ID_PERE)
 Values
   (7, 'Formation transversale', NULL, NULL, NULL, SYSDATE, SYSDATE, 7);
Insert into GRHUM.FORMATION_PERSONNEL
   (FOR_ID, FOR_LIBELLE, FOR_COMMENTAIRE, FOR_D_OUVERTURE, FOR_D_FERMETURE, 
    D_CREATION, D_MODIFICATION, FOR_ID_PERE)
 Values
   (8, 'Hygiène et sécurité', NULL, NULL, NULL, SYSDATE, SYSDATE, 8);
Insert into GRHUM.FORMATION_PERSONNEL
   (FOR_ID, FOR_LIBELLE, FOR_COMMENTAIRE, FOR_D_OUVERTURE, FOR_D_FERMETURE, 
    D_CREATION, D_MODIFICATION, FOR_ID_PERE)
 Values
   (9, 'Langues étrangéres', NULL, NULL, NULL, SYSDATE, SYSDATE, 9);
Insert into GRHUM.FORMATION_PERSONNEL
   (FOR_ID, FOR_LIBELLE, FOR_COMMENTAIRE, FOR_D_OUVERTURE, FOR_D_FERMETURE, 
    D_CREATION, D_MODIFICATION, FOR_ID_PERE)
 Values
   (10, 'Formations scientifiques', NULL, NULL, NULL, SYSDATE, SYSDATE, 10);
Insert into GRHUM.FORMATION_PERSONNEL
   (FOR_ID, FOR_LIBELLE, FOR_COMMENTAIRE, FOR_D_OUVERTURE, FOR_D_FERMETURE, 
    D_CREATION, D_MODIFICATION, FOR_ID_PERE)
 Values
   (12, 'Management', NULL, NULL, NULL, SYSDATE, SYSDATE, 3);
Insert into GRHUM.FORMATION_PERSONNEL
   (FOR_ID, FOR_LIBELLE, FOR_COMMENTAIRE, FOR_D_OUVERTURE, FOR_D_FERMETURE, 
    D_CREATION, D_MODIFICATION, FOR_ID_PERE)
 Values
   (13, 'Formations juridiques', NULL, NULL, NULL, SYSDATE, SYSDATE, 3);
Insert into GRHUM.FORMATION_PERSONNEL
   (FOR_ID, FOR_LIBELLE, FOR_COMMENTAIRE, FOR_D_OUVERTURE, FOR_D_FERMETURE, 
    D_CREATION, D_MODIFICATION, FOR_ID_PERE)
 Values
   (14, 'Gestion de l''étudiant', NULL, NULL, NULL, SYSDATE, SYSDATE, 3);
Insert into GRHUM.FORMATION_PERSONNEL
   (FOR_ID, FOR_LIBELLE, FOR_COMMENTAIRE, FOR_D_OUVERTURE, FOR_D_FERMETURE, 
    D_CREATION, D_MODIFICATION, FOR_ID_PERE)
 Values
   (15, 'Gestion et comptabilité', NULL, NULL, NULL, SYSDATE, SYSDATE, 3);
Insert into GRHUM.FORMATION_PERSONNEL
   (FOR_ID, FOR_LIBELLE, FOR_COMMENTAIRE, FOR_D_OUVERTURE, FOR_D_FERMETURE, 
    D_CREATION, D_MODIFICATION, FOR_ID_PERE)
 Values
   (16, 'Administration et institutions', NULL, NULL, NULL, SYSDATE, SYSDATE, 3);
Insert into GRHUM.FORMATION_PERSONNEL
   (FOR_ID, FOR_LIBELLE, FOR_COMMENTAIRE, FOR_D_OUVERTURE, FOR_D_FERMETURE, 
    D_CREATION, D_MODIFICATION, FOR_ID_PERE)
 Values
   (17, 'Gestion des ressources humaines', NULL, NULL, NULL, SYSDATE, SYSDATE, 3);
Insert into GRHUM.FORMATION_PERSONNEL
   (FOR_ID, FOR_LIBELLE, FOR_COMMENTAIRE, FOR_D_OUVERTURE, FOR_D_FERMETURE, 
    D_CREATION, D_MODIFICATION, FOR_ID_PERE)
 Values
   (18, 'Administratif - droit - finances', NULL, NULL, NULL, SYSDATE, SYSDATE, 3);
Insert into GRHUM.FORMATION_PERSONNEL
   (FOR_ID, FOR_LIBELLE, FOR_COMMENTAIRE, FOR_D_OUVERTURE, FOR_D_FERMETURE, 
    D_CREATION, D_MODIFICATION, FOR_ID_PERE)
 Values
   (20, 'Développement personnel', NULL, NULL, NULL, SYSDATE, SYSDATE, 7);
Insert into GRHUM.FORMATION_PERSONNEL
   (FOR_ID, FOR_LIBELLE, FOR_COMMENTAIRE, FOR_D_OUVERTURE, FOR_D_FERMETURE, 
    D_CREATION, D_MODIFICATION, FOR_ID_PERE)
 Values
   (21, 'Environnement professionnel', NULL, NULL, NULL, SYSDATE, SYSDATE, 7);
Insert into GRHUM.FORMATION_PERSONNEL
   (FOR_ID, FOR_LIBELLE, FOR_COMMENTAIRE, FOR_D_OUVERTURE, FOR_D_FERMETURE, 
    D_CREATION, D_MODIFICATION, FOR_ID_PERE)
 Values
   (24, 'Autres', NULL, NULL, NULL, SYSDATE, SYSDATE, 4);
Insert into GRHUM.FORMATION_PERSONNEL
   (FOR_ID, FOR_LIBELLE, FOR_COMMENTAIRE, FOR_D_OUVERTURE, FOR_D_FERMETURE, 
    D_CREATION, D_MODIFICATION, FOR_ID_PERE)
 Values
   (25, 'Bureautique', NULL, NULL, NULL, SYSDATE, SYSDATE, 4);
Insert into GRHUM.FORMATION_PERSONNEL
   (FOR_ID, FOR_LIBELLE, FOR_COMMENTAIRE, FOR_D_OUVERTURE, FOR_D_FERMETURE, 
    D_CREATION, D_MODIFICATION, FOR_ID_PERE)
 Values
   (26, 'Outils multimédia', NULL, NULL, NULL, SYSDATE, SYSDATE, 4);
Insert into GRHUM.FORMATION_PERSONNEL
   (FOR_ID, FOR_LIBELLE, FOR_COMMENTAIRE, FOR_D_OUVERTURE, FOR_D_FERMETURE, 
    D_CREATION, D_MODIFICATION, FOR_ID_PERE)
 Values
   (27, 'Applications de gestion', NULL, NULL, NULL, SYSDATE, SYSDATE, 4);
Insert into GRHUM.FORMATION_PERSONNEL
   (FOR_ID, FOR_LIBELLE, FOR_COMMENTAIRE, FOR_D_OUVERTURE, FOR_D_FERMETURE, 
    D_CREATION, D_MODIFICATION, FOR_ID_PERE)
 Values
   (28, 'Technicité informatique', NULL, NULL, NULL, SYSDATE, SYSDATE, 4);
Insert into GRHUM.FORMATION_PERSONNEL
   (FOR_ID, FOR_LIBELLE, FOR_COMMENTAIRE, FOR_D_OUVERTURE, FOR_D_FERMETURE, 
    D_CREATION, D_MODIFICATION, FOR_ID_PERE)
 Values
   (29, 'Langages et bases de données', NULL, NULL, NULL, SYSDATE, SYSDATE, 4);
Insert into GRHUM.FORMATION_PERSONNEL
   (FOR_ID, FOR_LIBELLE, FOR_COMMENTAIRE, FOR_D_OUVERTURE, FOR_D_FERMETURE, 
    D_CREATION, D_MODIFICATION, FOR_ID_PERE)
 Values
   (30, 'Applications / logiciels métiers', NULL, NULL, NULL, SYSDATE, SYSDATE, 4);
Insert into GRHUM.FORMATION_PERSONNEL
   (FOR_ID, FOR_LIBELLE, FOR_COMMENTAIRE, FOR_D_OUVERTURE, FOR_D_FERMETURE, 
    D_CREATION, D_MODIFICATION, FOR_ID_PERE)
 Values
   (31, 'Technologies d''information et de communication', NULL, NULL, NULL, SYSDATE, SYSDATE, 4);
Insert into GRHUM.FORMATION_PERSONNEL
   (FOR_ID, FOR_LIBELLE, FOR_COMMENTAIRE, FOR_D_OUVERTURE, FOR_D_FERMETURE, 
    D_CREATION, D_MODIFICATION, FOR_ID_PERE)
 Values
   (32, 'Autres', NULL, NULL, NULL, SYSDATE, SYSDATE, 6);
Insert into GRHUM.FORMATION_PERSONNEL
   (FOR_ID, FOR_LIBELLE, FOR_COMMENTAIRE, FOR_D_OUVERTURE, FOR_D_FERMETURE, 
    D_CREATION, D_MODIFICATION, FOR_ID_PERE)
 Values
   (33, 'Préparation aux concours', NULL, NULL, NULL, SYSDATE, SYSDATE, 6);
Insert into GRHUM.FORMATION_PERSONNEL
   (FOR_ID, FOR_LIBELLE, FOR_COMMENTAIRE, FOR_D_OUVERTURE, FOR_D_FERMETURE, 
    D_CREATION, D_MODIFICATION, FOR_ID_PERE)
 Values
   (35, 'VAE', NULL, NULL, NULL, SYSDATE, SYSDATE, 32);
Insert into GRHUM.FORMATION_PERSONNEL
   (FOR_ID, FOR_LIBELLE, FOR_COMMENTAIRE, FOR_D_OUVERTURE, FOR_D_FERMETURE, 
    D_CREATION, D_MODIFICATION, FOR_ID_PERE)
 Values
   (36, 'VAE', NULL, NULL, NULL, SYSDATE, SYSDATE, 24);
Insert into GRHUM.FORMATION_PERSONNEL
   (FOR_ID, FOR_LIBELLE, FOR_COMMENTAIRE, FOR_D_OUVERTURE, FOR_D_FERMETURE, 
    D_CREATION, D_MODIFICATION, FOR_ID_PERE)
 Values
   (37, 'DAEU', NULL, NULL, NULL, SYSDATE, SYSDATE, 32);
Insert into GRHUM.FORMATION_PERSONNEL
   (FOR_ID, FOR_LIBELLE, FOR_COMMENTAIRE, FOR_D_OUVERTURE, FOR_D_FERMETURE, 
    D_CREATION, D_MODIFICATION, FOR_ID_PERE)
 Values
   (38, 'DAEU', NULL, NULL, NULL, SYSDATE, SYSDATE, 24);
Insert into GRHUM.FORMATION_PERSONNEL
   (FOR_ID, FOR_LIBELLE, FOR_COMMENTAIRE, FOR_D_OUVERTURE, FOR_D_FERMETURE, 
    D_CREATION, D_MODIFICATION, FOR_ID_PERE)
 Values
   (39, 'auto-commutateur', NULL, NULL, NULL, SYSDATE, SYSDATE, 32);
Insert into GRHUM.FORMATION_PERSONNEL
   (FOR_ID, FOR_LIBELLE, FOR_COMMENTAIRE, FOR_D_OUVERTURE, FOR_D_FERMETURE, 
    D_CREATION, D_MODIFICATION, FOR_ID_PERE)
 Values
   (40, 'auto-commutateur', NULL, NULL, NULL, SYSDATE, SYSDATE, 24);
Insert into GRHUM.FORMATION_PERSONNEL
   (FOR_ID, FOR_LIBELLE, FOR_COMMENTAIRE, FOR_D_OUVERTURE, FOR_D_FERMETURE, 
    D_CREATION, D_MODIFICATION, FOR_ID_PERE)
 Values
   (41, 'maintenance audiovisuelle', NULL, NULL, NULL, SYSDATE, SYSDATE, 32);
Insert into GRHUM.FORMATION_PERSONNEL
   (FOR_ID, FOR_LIBELLE, FOR_COMMENTAIRE, FOR_D_OUVERTURE, FOR_D_FERMETURE, 
    D_CREATION, D_MODIFICATION, FOR_ID_PERE)
 Values
   (42, 'maintenance audiovisuelle', NULL, NULL, NULL, SYSDATE, SYSDATE, 24);
Insert into GRHUM.FORMATION_PERSONNEL
   (FOR_ID, FOR_LIBELLE, FOR_COMMENTAIRE, FOR_D_OUVERTURE, FOR_D_FERMETURE, 
    D_CREATION, D_MODIFICATION, FOR_ID_PERE)
 Values
   (43, 'Exploitation et entretien du matériel audiovisuel', NULL, NULL, NULL, SYSDATE, SYSDATE, 32);
Insert into GRHUM.FORMATION_PERSONNEL
   (FOR_ID, FOR_LIBELLE, FOR_COMMENTAIRE, FOR_D_OUVERTURE, FOR_D_FERMETURE, 
    D_CREATION, D_MODIFICATION, FOR_ID_PERE)
 Values
   (44, 'Exploitation et entretien du matériel audiovisuel', NULL, NULL, NULL, SYSDATE, SYSDATE, 24);
Insert into GRHUM.FORMATION_PERSONNEL
   (FOR_ID, FOR_LIBELLE, FOR_COMMENTAIRE, FOR_D_OUVERTURE, FOR_D_FERMETURE, 
    D_CREATION, D_MODIFICATION, FOR_ID_PERE)
 Values
   (45, 'Première maintenance de matériel, rétroprojecteurs et informatique', NULL, NULL, NULL, SYSDATE, SYSDATE, 32);
Insert into GRHUM.FORMATION_PERSONNEL
   (FOR_ID, FOR_LIBELLE, FOR_COMMENTAIRE, FOR_D_OUVERTURE, FOR_D_FERMETURE, 
    D_CREATION, D_MODIFICATION, FOR_ID_PERE)
 Values
   (46, 'Première maintenance de matériel, rétroprojecteurs et informatique', NULL, NULL, NULL, SYSDATE, SYSDATE, 24);
Insert into GRHUM.FORMATION_PERSONNEL
   (FOR_ID, FOR_LIBELLE, FOR_COMMENTAIRE, FOR_D_OUVERTURE, FOR_D_FERMETURE, 
    D_CREATION, D_MODIFICATION, FOR_ID_PERE)
 Values
   (47, 'Conduite de projet', NULL, NULL, NULL, SYSDATE, SYSDATE, 12);
Insert into GRHUM.FORMATION_PERSONNEL
   (FOR_ID, FOR_LIBELLE, FOR_COMMENTAIRE, FOR_D_OUVERTURE, FOR_D_FERMETURE, 
    D_CREATION, D_MODIFICATION, FOR_ID_PERE)
 Values
   (48, 'Conduite de réunion', NULL, NULL, NULL, SYSDATE, SYSDATE, 12);
Insert into GRHUM.FORMATION_PERSONNEL
   (FOR_ID, FOR_LIBELLE, FOR_COMMENTAIRE, FOR_D_OUVERTURE, FOR_D_FERMETURE, 
    D_CREATION, D_MODIFICATION, FOR_ID_PERE)
 Values
   (49, 'Animer une équipe de travail', NULL, NULL, NULL, SYSDATE, SYSDATE, 12);
Insert into GRHUM.FORMATION_PERSONNEL
   (FOR_ID, FOR_LIBELLE, FOR_COMMENTAIRE, FOR_D_OUVERTURE, FOR_D_FERMETURE, 
    D_CREATION, D_MODIFICATION, FOR_ID_PERE)
 Values
   (50, 'Gestion d''un projet européen', NULL, NULL, NULL, SYSDATE, SYSDATE, 12);
Insert into GRHUM.FORMATION_PERSONNEL
   (FOR_ID, FOR_LIBELLE, FOR_COMMENTAIRE, FOR_D_OUVERTURE, FOR_D_FERMETURE, 
    D_CREATION, D_MODIFICATION, FOR_ID_PERE)
 Values
   (51, 'Initiation à la communication', NULL, NULL, NULL, SYSDATE, SYSDATE, 12);
Insert into GRHUM.FORMATION_PERSONNEL
   (FOR_ID, FOR_LIBELLE, FOR_COMMENTAIRE, FOR_D_OUVERTURE, FOR_D_FERMETURE, 
    D_CREATION, D_MODIFICATION, FOR_ID_PERE)
 Values
   (52, 'Management intégré de la qualité et de la performance', NULL, NULL, NULL, SYSDATE, SYSDATE, 12);
Insert into GRHUM.FORMATION_PERSONNEL
   (FOR_ID, FOR_LIBELLE, FOR_COMMENTAIRE, FOR_D_OUVERTURE, FOR_D_FERMETURE, 
    D_CREATION, D_MODIFICATION, FOR_ID_PERE)
 Values
   (53, 'POWERPOINT', NULL, NULL, NULL, SYSDATE, SYSDATE, 25);
Insert into GRHUM.FORMATION_PERSONNEL
   (FOR_ID, FOR_LIBELLE, FOR_COMMENTAIRE, FOR_D_OUVERTURE, FOR_D_FERMETURE, 
    D_CREATION, D_MODIFICATION, FOR_ID_PERE)
 Values
   (54, 'Dactylographie', NULL, NULL, NULL, SYSDATE, SYSDATE, 25);
Insert into GRHUM.FORMATION_PERSONNEL
   (FOR_ID, FOR_LIBELLE, FOR_COMMENTAIRE, FOR_D_OUVERTURE, FOR_D_FERMETURE, 
    D_CREATION, D_MODIFICATION, FOR_ID_PERE)
 Values
   (55, 'WORD - Initiation', NULL, NULL, NULL, SYSDATE, SYSDATE, 25);
Insert into GRHUM.FORMATION_PERSONNEL
   (FOR_ID, FOR_LIBELLE, FOR_COMMENTAIRE, FOR_D_OUVERTURE, FOR_D_FERMETURE, 
    D_CREATION, D_MODIFICATION, FOR_ID_PERE)
 Values
   (56, 'EXCEL - Initiation', NULL, NULL, NULL, SYSDATE, SYSDATE, 25);
Insert into GRHUM.FORMATION_PERSONNEL
   (FOR_ID, FOR_LIBELLE, FOR_COMMENTAIRE, FOR_D_OUVERTURE, FOR_D_FERMETURE, 
    D_CREATION, D_MODIFICATION, FOR_ID_PERE)
 Values
   (57, 'WORD - Perfectionnement', NULL, NULL, NULL, SYSDATE, SYSDATE, 25);
Insert into GRHUM.FORMATION_PERSONNEL
   (FOR_ID, FOR_LIBELLE, FOR_COMMENTAIRE, FOR_D_OUVERTURE, FOR_D_FERMETURE, 
    D_CREATION, D_MODIFICATION, FOR_ID_PERE)
 Values
   (58, 'EXCEL - Perfectionnement ', NULL, NULL, NULL, SYSDATE, SYSDATE, 25);
Insert into GRHUM.FORMATION_PERSONNEL
   (FOR_ID, FOR_LIBELLE, FOR_COMMENTAIRE, FOR_D_OUVERTURE, FOR_D_FERMETURE, 
    D_CREATION, D_MODIFICATION, FOR_ID_PERE)
 Values
   (59, 'Certificat Informatique et Internet (C2i)', NULL, NULL, NULL, SYSDATE, SYSDATE, 25);
Insert into GRHUM.FORMATION_PERSONNEL
   (FOR_ID, FOR_LIBELLE, FOR_COMMENTAIRE, FOR_D_OUVERTURE, FOR_D_FERMETURE, 
    D_CREATION, D_MODIFICATION, FOR_ID_PERE)
 Values
   (60, 'PAO', NULL, NULL, NULL, SYSDATE, SYSDATE, 26);
Insert into GRHUM.FORMATION_PERSONNEL
   (FOR_ID, FOR_LIBELLE, FOR_COMMENTAIRE, FOR_D_OUVERTURE, FOR_D_FERMETURE, 
    D_CREATION, D_MODIFICATION, FOR_ID_PERE)
 Values
   (61, 'Indesign', NULL, NULL, NULL, SYSDATE, SYSDATE, 26);
Insert into GRHUM.FORMATION_PERSONNEL
   (FOR_ID, FOR_LIBELLE, FOR_COMMENTAIRE, FOR_D_OUVERTURE, FOR_D_FERMETURE, 
    D_CREATION, D_MODIFICATION, FOR_ID_PERE)
 Values
   (62, 'Publisher', NULL, NULL, NULL, SYSDATE, SYSDATE, 26);
Insert into GRHUM.FORMATION_PERSONNEL
   (FOR_ID, FOR_LIBELLE, FOR_COMMENTAIRE, FOR_D_OUVERTURE, FOR_D_FERMETURE, 
    D_CREATION, D_MODIFICATION, FOR_ID_PERE)
 Values
   (63, 'Acrobat Pro', NULL, NULL, NULL, SYSDATE, SYSDATE, 26);
Insert into GRHUM.FORMATION_PERSONNEL
   (FOR_ID, FOR_LIBELLE, FOR_COMMENTAIRE, FOR_D_OUVERTURE, FOR_D_FERMETURE, 
    D_CREATION, D_MODIFICATION, FOR_ID_PERE)
 Values
   (64, 'DreamWeaver', NULL, NULL, NULL, SYSDATE, SYSDATE, 26);
Insert into GRHUM.FORMATION_PERSONNEL
   (FOR_ID, FOR_LIBELLE, FOR_COMMENTAIRE, FOR_D_OUVERTURE, FOR_D_FERMETURE, 
    D_CREATION, D_MODIFICATION, FOR_ID_PERE)
 Values
   (65, 'Logiciel Final Cut', NULL, NULL, NULL, SYSDATE, SYSDATE, 26);
Insert into GRHUM.FORMATION_PERSONNEL
   (FOR_ID, FOR_LIBELLE, FOR_COMMENTAIRE, FOR_D_OUVERTURE, FOR_D_FERMETURE, 
    D_CREATION, D_MODIFICATION, FOR_ID_PERE)
 Values
   (66, 'PHOTOSHOP - Initiation', NULL, NULL, NULL, SYSDATE, SYSDATE, 26);
Insert into GRHUM.FORMATION_PERSONNEL
   (FOR_ID, FOR_LIBELLE, FOR_COMMENTAIRE, FOR_D_OUVERTURE, FOR_D_FERMETURE, 
    D_CREATION, D_MODIFICATION, FOR_ID_PERE)
 Values
   (67, 'Outils de communication', NULL, NULL, NULL, SYSDATE, SYSDATE, 26);
Insert into GRHUM.FORMATION_PERSONNEL
   (FOR_ID, FOR_LIBELLE, FOR_COMMENTAIRE, FOR_D_OUVERTURE, FOR_D_FERMETURE, 
    D_CREATION, D_MODIFICATION, FOR_ID_PERE)
 Values
   (68, 'PHOTOSHOP -  Perfectionnement', NULL, NULL, NULL, SYSDATE, SYSDATE, 26);
Insert into GRHUM.FORMATION_PERSONNEL
   (FOR_ID, FOR_LIBELLE, FOR_COMMENTAIRE, FOR_D_OUVERTURE, FOR_D_FERMETURE, 
    D_CREATION, D_MODIFICATION, FOR_ID_PERE)
 Values
   (69, 'ANGLAIS oral', NULL, NULL, NULL, SYSDATE, SYSDATE, 9);
Insert into GRHUM.FORMATION_PERSONNEL
   (FOR_ID, FOR_LIBELLE, FOR_COMMENTAIRE, FOR_D_OUVERTURE, FOR_D_FERMETURE, 
    D_CREATION, D_MODIFICATION, FOR_ID_PERE)
 Values
   (70, 'ANGLAIS écrit', NULL, NULL, NULL, SYSDATE, SYSDATE, 9);
Insert into GRHUM.FORMATION_PERSONNEL
   (FOR_ID, FOR_LIBELLE, FOR_COMMENTAIRE, FOR_D_OUVERTURE, FOR_D_FERMETURE, 
    D_CREATION, D_MODIFICATION, FOR_ID_PERE)
 Values
   (71, 'Espagnol oral', NULL, NULL, NULL, SYSDATE, SYSDATE, 9);
Insert into GRHUM.FORMATION_PERSONNEL
   (FOR_ID, FOR_LIBELLE, FOR_COMMENTAIRE, FOR_D_OUVERTURE, FOR_D_FERMETURE, 
    D_CREATION, D_MODIFICATION, FOR_ID_PERE)
 Values
   (72, 'Espagnol écrit', NULL, NULL, NULL, SYSDATE, SYSDATE, 9);
Insert into GRHUM.FORMATION_PERSONNEL
   (FOR_ID, FOR_LIBELLE, FOR_COMMENTAIRE, FOR_D_OUVERTURE, FOR_D_FERMETURE, 
    D_CREATION, D_MODIFICATION, FOR_ID_PERE)
 Values
   (73, 'PSC1', NULL, NULL, NULL, SYSDATE, SYSDATE, 8);
Insert into GRHUM.FORMATION_PERSONNEL
   (FOR_ID, FOR_LIBELLE, FOR_COMMENTAIRE, FOR_D_OUVERTURE, FOR_D_FERMETURE, 
    D_CREATION, D_MODIFICATION, FOR_ID_PERE)
 Values
   (74, 'A.C.M.O.', NULL, NULL, NULL, SYSDATE, SYSDATE, 8);
Insert into GRHUM.FORMATION_PERSONNEL
   (FOR_ID, FOR_LIBELLE, FOR_COMMENTAIRE, FOR_D_OUVERTURE, FOR_D_FERMETURE, 
    D_CREATION, D_MODIFICATION, FOR_ID_PERE)
 Values
   (75, 'SERRE-FILES', NULL, NULL, NULL, SYSDATE, SYSDATE, 8);
Insert into GRHUM.FORMATION_PERSONNEL
   (FOR_ID, FOR_LIBELLE, FOR_COMMENTAIRE, FOR_D_OUVERTURE, FOR_D_FERMETURE, 
    D_CREATION, D_MODIFICATION, FOR_ID_PERE)
 Values
   (76, 'Recyclage AFPS', NULL, NULL, NULL, SYSDATE, SYSDATE, 8);
Insert into GRHUM.FORMATION_PERSONNEL
   (FOR_ID, FOR_LIBELLE, FOR_COMMENTAIRE, FOR_D_OUVERTURE, FOR_D_FERMETURE, 
    D_CREATION, D_MODIFICATION, FOR_ID_PERE)
 Values
   (77, 'Recyclage PSC1', NULL, NULL, NULL, SYSDATE, SYSDATE, 8);
Insert into GRHUM.FORMATION_PERSONNEL
   (FOR_ID, FOR_LIBELLE, FOR_COMMENTAIRE, FOR_D_OUVERTURE, FOR_D_FERMETURE, 
    D_CREATION, D_MODIFICATION, FOR_ID_PERE)
 Values
   (78, 'Recyclage SSIAP 1', NULL, NULL, NULL, SYSDATE, SYSDATE, 8);
Insert into GRHUM.FORMATION_PERSONNEL
   (FOR_ID, FOR_LIBELLE, FOR_COMMENTAIRE, FOR_D_OUVERTURE, FOR_D_FERMETURE, 
    D_CREATION, D_MODIFICATION, FOR_ID_PERE)
 Values
   (79, 'Sécurité incendie', NULL, NULL, NULL, SYSDATE, SYSDATE, 8);
Insert into GRHUM.FORMATION_PERSONNEL
   (FOR_ID, FOR_LIBELLE, FOR_COMMENTAIRE, FOR_D_OUVERTURE, FOR_D_FERMETURE, 
    D_CREATION, D_MODIFICATION, FOR_ID_PERE)
 Values
   (80, 'Gestion des déchets', NULL, NULL, NULL, SYSDATE, SYSDATE, 8);
Insert into GRHUM.FORMATION_PERSONNEL
   (FOR_ID, FOR_LIBELLE, FOR_COMMENTAIRE, FOR_D_OUVERTURE, FOR_D_FERMETURE, 
    D_CREATION, D_MODIFICATION, FOR_ID_PERE)
 Values
   (81, 'Recyclage S.S.I.A.P.2', NULL, NULL, NULL, SYSDATE, SYSDATE, 8);
Insert into GRHUM.FORMATION_PERSONNEL
   (FOR_ID, FOR_LIBELLE, FOR_COMMENTAIRE, FOR_D_OUVERTURE, FOR_D_FERMETURE, 
    D_CREATION, D_MODIFICATION, FOR_ID_PERE)
 Values
   (82, 'Formation ACMO (formateur)', NULL, NULL, NULL, SYSDATE, SYSDATE, 8);
Insert into GRHUM.FORMATION_PERSONNEL
   (FOR_ID, FOR_LIBELLE, FOR_COMMENTAIRE, FOR_D_OUVERTURE, FOR_D_FERMETURE, 
    D_CREATION, D_MODIFICATION, FOR_ID_PERE)
 Values
   (83, 'Formation initiale des CLHS', NULL, NULL, NULL, SYSDATE, SYSDATE, 8);
Insert into GRHUM.FORMATION_PERSONNEL
   (FOR_ID, FOR_LIBELLE, FOR_COMMENTAIRE, FOR_D_OUVERTURE, FOR_D_FERMETURE, 
    D_CREATION, D_MODIFICATION, FOR_ID_PERE)
 Values
   (84, 'Prévention des toxicomanies', NULL, NULL, NULL, SYSDATE, SYSDATE, 8);
Insert into GRHUM.FORMATION_PERSONNEL
   (FOR_ID, FOR_LIBELLE, FOR_COMMENTAIRE, FOR_D_OUVERTURE, FOR_D_FERMETURE, 
    D_CREATION, D_MODIFICATION, FOR_ID_PERE)
 Values
   (85, 'Habilitation PCR - recyclage', NULL, NULL, NULL, SYSDATE, SYSDATE, 8);
Insert into GRHUM.FORMATION_PERSONNEL
   (FOR_ID, FOR_LIBELLE, FOR_COMMENTAIRE, FOR_D_OUVERTURE, FOR_D_FERMETURE, 
    D_CREATION, D_MODIFICATION, FOR_ID_PERE)
 Values
   (86, 'PREVENTION DU RISQUE AMIANTE', NULL, NULL, NULL, SYSDATE, SYSDATE, 8);
Insert into GRHUM.FORMATION_PERSONNEL
   (FOR_ID, FOR_LIBELLE, FOR_COMMENTAIRE, FOR_D_OUVERTURE, FOR_D_FERMETURE, 
    D_CREATION, D_MODIFICATION, FOR_ID_PERE)
 Values
   (87, 'Adaptation aux nouveau locaux', NULL, NULL, NULL, SYSDATE, SYSDATE, 8);
Insert into GRHUM.FORMATION_PERSONNEL
   (FOR_ID, FOR_LIBELLE, FOR_COMMENTAIRE, FOR_D_OUVERTURE, FOR_D_FERMETURE, 
    D_CREATION, D_MODIFICATION, FOR_ID_PERE)
 Values
   (88, 'Gestion des déchets chimiques', NULL, NULL, NULL, SYSDATE, SYSDATE, 8);
Insert into GRHUM.FORMATION_PERSONNEL
   (FOR_ID, FOR_LIBELLE, FOR_COMMENTAIRE, FOR_D_OUVERTURE, FOR_D_FERMETURE, 
    D_CREATION, D_MODIFICATION, FOR_ID_PERE)
 Values
   (89, 'Prévention du risque incendie', NULL, NULL, NULL, SYSDATE, SYSDATE, 8);
Insert into GRHUM.FORMATION_PERSONNEL
   (FOR_ID, FOR_LIBELLE, FOR_COMMENTAIRE, FOR_D_OUVERTURE, FOR_D_FERMETURE, 
    D_CREATION, D_MODIFICATION, FOR_ID_PERE)
 Values
   (90, 'Formation aux premiers secours', NULL, NULL, NULL, SYSDATE, SYSDATE, 8);
Insert into GRHUM.FORMATION_PERSONNEL
   (FOR_ID, FOR_LIBELLE, FOR_COMMENTAIRE, FOR_D_OUVERTURE, FOR_D_FERMETURE, 
    D_CREATION, D_MODIFICATION, FOR_ID_PERE)
 Values
   (91, 'Sécurité incendie dans les ERP', NULL, NULL, NULL, SYSDATE, SYSDATE, 8);
Insert into GRHUM.FORMATION_PERSONNEL
   (FOR_ID, FOR_LIBELLE, FOR_COMMENTAIRE, FOR_D_OUVERTURE, FOR_D_FERMETURE, 
    D_CREATION, D_MODIFICATION, FOR_ID_PERE)
 Values
   (92, 'CACES plates-formes élévatrices', NULL, NULL, NULL, SYSDATE, SYSDATE, 8);
Insert into GRHUM.FORMATION_PERSONNEL
   (FOR_ID, FOR_LIBELLE, FOR_COMMENTAIRE, FOR_D_OUVERTURE, FOR_D_FERMETURE, 
    D_CREATION, D_MODIFICATION, FOR_ID_PERE)
 Values
   (93, 'Montage d''une tour d''échafaudage', NULL, NULL, NULL, SYSDATE, SYSDATE, 8);
Insert into GRHUM.FORMATION_PERSONNEL
   (FOR_ID, FOR_LIBELLE, FOR_COMMENTAIRE, FOR_D_OUVERTURE, FOR_D_FERMETURE, 
    D_CREATION, D_MODIFICATION, FOR_ID_PERE)
 Values
   (94, 'Entretien et hygiène au laboratoire', NULL, NULL, NULL, SYSDATE, SYSDATE, 8);
Insert into GRHUM.FORMATION_PERSONNEL
   (FOR_ID, FOR_LIBELLE, FOR_COMMENTAIRE, FOR_D_OUVERTURE, FOR_D_FERMETURE, 
    D_CREATION, D_MODIFICATION, FOR_ID_PERE)
 Values
   (95, 'Expérimentation animale  (niveau I)', NULL, NULL, NULL, SYSDATE, SYSDATE, 8);
Insert into GRHUM.FORMATION_PERSONNEL
   (FOR_ID, FOR_LIBELLE, FOR_COMMENTAIRE, FOR_D_OUVERTURE, FOR_D_FERMETURE, 
    D_CREATION, D_MODIFICATION, FOR_ID_PERE)
 Values
   (96, 'Formation à l''expérimentation animale', NULL, NULL, NULL, SYSDATE, SYSDATE, 8);
Insert into GRHUM.FORMATION_PERSONNEL
   (FOR_ID, FOR_LIBELLE, FOR_COMMENTAIRE, FOR_D_OUVERTURE, FOR_D_FERMETURE, 
    D_CREATION, D_MODIFICATION, FOR_ID_PERE)
 Values
   (97, 'Manipulation de la centrale incendie ', NULL, NULL, NULL, SYSDATE, SYSDATE, 8);
Insert into GRHUM.FORMATION_PERSONNEL
   (FOR_ID, FOR_LIBELLE, FOR_COMMENTAIRE, FOR_D_OUVERTURE, FOR_D_FERMETURE, 
    D_CREATION, D_MODIFICATION, FOR_ID_PERE)
 Values
   (98, 'Recyclage en  habilitation électrique', NULL, NULL, NULL, SYSDATE, SYSDATE, 8);
Insert into GRHUM.FORMATION_PERSONNEL
   (FOR_ID, FOR_LIBELLE, FOR_COMMENTAIRE, FOR_D_OUVERTURE, FOR_D_FERMETURE, 
    D_CREATION, D_MODIFICATION, FOR_ID_PERE)
 Values
   (99, 'Manipulation extincteurs et évacuation', NULL, NULL, NULL, SYSDATE, SYSDATE, 8);
Insert into GRHUM.FORMATION_PERSONNEL
   (FOR_ID, FOR_LIBELLE, FOR_COMMENTAIRE, FOR_D_OUVERTURE, FOR_D_FERMETURE, 
    D_CREATION, D_MODIFICATION, FOR_ID_PERE)
 Values
   (100, 'Personne compétente en radioprotection', NULL, NULL, NULL, SYSDATE, SYSDATE, 8);
Insert into GRHUM.FORMATION_PERSONNEL
   (FOR_ID, FOR_LIBELLE, FOR_COMMENTAIRE, FOR_D_OUVERTURE, FOR_D_FERMETURE, 
    D_CREATION, D_MODIFICATION, FOR_ID_PERE)
 Values
   (101, 'Postes et postures - Travail sur écran', NULL, NULL, NULL, SYSDATE, SYSDATE, 8);
Insert into GRHUM.FORMATION_PERSONNEL
   (FOR_ID, FOR_LIBELLE, FOR_COMMENTAIRE, FOR_D_OUVERTURE, FOR_D_FERMETURE, 
    D_CREATION, D_MODIFICATION, FOR_ID_PERE)
 Values
   (102, 'Habilitation à la conduite d''autoclaves', NULL, NULL, NULL, SYSDATE, SYSDATE, 8);
Insert into GRHUM.FORMATION_PERSONNEL
   (FOR_ID, FOR_LIBELLE, FOR_COMMENTAIRE, FOR_D_OUVERTURE, FOR_D_FERMETURE, 
    D_CREATION, D_MODIFICATION, FOR_ID_PERE)
 Values
   (103, 'L''évaluation des risques professionnels', NULL, NULL, NULL, SYSDATE, SYSDATE, 8);
Insert into GRHUM.FORMATION_PERSONNEL
   (FOR_ID, FOR_LIBELLE, FOR_COMMENTAIRE, FOR_D_OUVERTURE, FOR_D_FERMETURE, 
    D_CREATION, D_MODIFICATION, FOR_ID_PERE)
 Values
   (104, 'Habilitation à la  conduite d''autoclaves', NULL, NULL, NULL, SYSDATE, SYSDATE, 8);
Insert into GRHUM.FORMATION_PERSONNEL
   (FOR_ID, FOR_LIBELLE, FOR_COMMENTAIRE, FOR_D_OUVERTURE, FOR_D_FERMETURE, 
    D_CREATION, D_MODIFICATION, FOR_ID_PERE)
 Values
   (105, 'La prévention des risques professionnels', NULL, NULL, NULL, SYSDATE, SYSDATE, 8);
Insert into GRHUM.FORMATION_PERSONNEL
   (FOR_ID, FOR_LIBELLE, FOR_COMMENTAIRE, FOR_D_OUVERTURE, FOR_D_FERMETURE, 
    D_CREATION, D_MODIFICATION, FOR_ID_PERE)
 Values
   (106, 'Prévenir et gérer les risques contentieux', NULL, NULL, NULL, SYSDATE, SYSDATE, 8);
Insert into GRHUM.FORMATION_PERSONNEL
   (FOR_ID, FOR_LIBELLE, FOR_COMMENTAIRE, FOR_D_OUVERTURE, FOR_D_FERMETURE, 
    D_CREATION, D_MODIFICATION, FOR_ID_PERE)
 Values
   (107, 'Responsabilités et nouveau code du travail', NULL, NULL, NULL, SYSDATE, SYSDATE, 8);
Insert into GRHUM.FORMATION_PERSONNEL
   (FOR_ID, FOR_LIBELLE, FOR_COMMENTAIRE, FOR_D_OUVERTURE, FOR_D_FERMETURE, 
    D_CREATION, D_MODIFICATION, FOR_ID_PERE)
 Values
   (108, 'Hygiène et sécurité : nouveau code du travail', NULL, NULL, NULL, SYSDATE, SYSDATE, 8);
Insert into GRHUM.FORMATION_PERSONNEL
   (FOR_ID, FOR_LIBELLE, FOR_COMMENTAIRE, FOR_D_OUVERTURE, FOR_D_FERMETURE, 
    D_CREATION, D_MODIFICATION, FOR_ID_PERE)
 Values
   (109, 'Formation sécurité pour les nouveaux arrivants', NULL, NULL, NULL, SYSDATE, SYSDATE, 8);
Insert into GRHUM.FORMATION_PERSONNEL
   (FOR_ID, FOR_LIBELLE, FOR_COMMENTAIRE, FOR_D_OUVERTURE, FOR_D_FERMETURE, 
    D_CREATION, D_MODIFICATION, FOR_ID_PERE)
 Values
   (110, 'Formation membres du Comité Hygiène et Sécurité', NULL, NULL, NULL, SYSDATE, SYSDATE, 8);
Insert into GRHUM.FORMATION_PERSONNEL
   (FOR_ID, FOR_LIBELLE, FOR_COMMENTAIRE, FOR_D_OUVERTURE, FOR_D_FERMETURE, 
    D_CREATION, D_MODIFICATION, FOR_ID_PERE)
 Values
   (111, 'Equipier de seconde intervention et d''évacuation', NULL, NULL, NULL, SYSDATE, SYSDATE, 8);
Insert into GRHUM.FORMATION_PERSONNEL
   (FOR_ID, FOR_LIBELLE, FOR_COMMENTAIRE, FOR_D_OUVERTURE, FOR_D_FERMETURE, 
    D_CREATION, D_MODIFICATION, FOR_ID_PERE)
 Values
   (112, 'Le risque biologique en laboratoire de recherche', NULL, NULL, NULL, SYSDATE, SYSDATE, 8);
Insert into GRHUM.FORMATION_PERSONNEL
   (FOR_ID, FOR_LIBELLE, FOR_COMMENTAIRE, FOR_D_OUVERTURE, FOR_D_FERMETURE, 
    D_CREATION, D_MODIFICATION, FOR_ID_PERE)
 Values
   (113, 'Formation membres CHS et correspondants locaux HS', NULL, NULL, NULL, SYSDATE, SYSDATE, 8);
Insert into GRHUM.FORMATION_PERSONNEL
   (FOR_ID, FOR_LIBELLE, FOR_COMMENTAIRE, FOR_D_OUVERTURE, FOR_D_FERMETURE, 
    D_CREATION, D_MODIFICATION, FOR_ID_PERE)
 Values
   (114, 'Ponts roulants pontiers -  conducteurs expérimentés', NULL, NULL, NULL, SYSDATE, SYSDATE, 8);
Insert into GRHUM.FORMATION_PERSONNEL
   (FOR_ID, FOR_LIBELLE, FOR_COMMENTAIRE, FOR_D_OUVERTURE, FOR_D_FERMETURE, 
    D_CREATION, D_MODIFICATION, FOR_ID_PERE)
 Values
   (115, 'HABILITATION ELECTRIQUE (enseignants et techniciens)', NULL, NULL, NULL, SYSDATE, SYSDATE, 8);
Insert into GRHUM.FORMATION_PERSONNEL
   (FOR_ID, FOR_LIBELLE, FOR_COMMENTAIRE, FOR_D_OUVERTURE, FOR_D_FERMETURE, 
    D_CREATION, D_MODIFICATION, FOR_ID_PERE)
 Values
   (116, 'PYLA B sécurité laser, règles, consignes, procédures', NULL, NULL, NULL, SYSDATE, SYSDATE, 8);
Insert into GRHUM.FORMATION_PERSONNEL
   (FOR_ID, FOR_LIBELLE, FOR_COMMENTAIRE, FOR_D_OUVERTURE, FOR_D_FERMETURE, 
    D_CREATION, D_MODIFICATION, FOR_ID_PERE)
 Values
   (117, 'Utilisation de précurseurs chimiques en laboratoires', NULL, NULL, NULL, SYSDATE, SYSDATE, 8);
Insert into GRHUM.FORMATION_PERSONNEL
   (FOR_ID, FOR_LIBELLE, FOR_COMMENTAIRE, FOR_D_OUVERTURE, FOR_D_FERMETURE, 
    D_CREATION, D_MODIFICATION, FOR_ID_PERE)
 Values
   (118, 'Chef d''équipe en sécurité incendie dans les ERP (ERP2)', NULL, NULL, NULL, SYSDATE, SYSDATE, 8);
Insert into GRHUM.FORMATION_PERSONNEL
   (FOR_ID, FOR_LIBELLE, FOR_COMMENTAIRE, FOR_D_OUVERTURE, FOR_D_FERMETURE, 
    D_CREATION, D_MODIFICATION, FOR_ID_PERE)
 Values
   (119, 'Serre-file - Organisation sécurité incendie - évacuation', NULL, NULL, NULL, SYSDATE, SYSDATE, 8);
Insert into GRHUM.FORMATION_PERSONNEL
   (FOR_ID, FOR_LIBELLE, FOR_COMMENTAIRE, FOR_D_OUVERTURE, FOR_D_FERMETURE, 
    D_CREATION, D_MODIFICATION, FOR_ID_PERE)
 Values
   (120, 'Exploitation d''une chaufferie à vapeur ou eau surchauffée', NULL, NULL, NULL, SYSDATE, SYSDATE, 8);
Insert into GRHUM.FORMATION_PERSONNEL
   (FOR_ID, FOR_LIBELLE, FOR_COMMENTAIRE, FOR_D_OUVERTURE, FOR_D_FERMETURE, 
    D_CREATION, D_MODIFICATION, FOR_ID_PERE)
 Values
   (121, 'Sécurité et sûreté biologiques dans la pratique quotidienne', NULL, NULL, NULL, SYSDATE, SYSDATE, 8);
Insert into GRHUM.FORMATION_PERSONNEL
   (FOR_ID, FOR_LIBELLE, FOR_COMMENTAIRE, FOR_D_OUVERTURE, FOR_D_FERMETURE, 
    D_CREATION, D_MODIFICATION, FOR_ID_PERE)
 Values
   (122, 'Utilisation d''une chaudière à vapeur de puissance électrique', NULL, NULL, NULL, SYSDATE, SYSDATE, 8);
Insert into GRHUM.FORMATION_PERSONNEL
   (FOR_ID, FOR_LIBELLE, FOR_COMMENTAIRE, FOR_D_OUVERTURE, FOR_D_FERMETURE, 
    D_CREATION, D_MODIFICATION, FOR_ID_PERE)
 Values
   (123, 'Le risque chimique en laboratoire - Description et prévention', NULL, NULL, NULL, SYSDATE, SYSDATE, 8);
Insert into GRHUM.FORMATION_PERSONNEL
   (FOR_ID, FOR_LIBELLE, FOR_COMMENTAIRE, FOR_D_OUVERTURE, FOR_D_FERMETURE, 
    D_CREATION, D_MODIFICATION, FOR_ID_PERE)
 Values
   (124, 'HABILITATION ELECTRIQUE(personnels techniques non électriciens)', NULL, NULL, NULL, SYSDATE, SYSDATE, 8);
Insert into GRHUM.FORMATION_PERSONNEL
   (FOR_ID, FOR_LIBELLE, FOR_COMMENTAIRE, FOR_D_OUVERTURE, FOR_D_FERMETURE, 
    D_CREATION, D_MODIFICATION, FOR_ID_PERE)
 Values
   (125, 'Accueil des personnes handicapées dans les Ets d''Ens. Supérieurs', NULL, NULL, NULL, SYSDATE, SYSDATE, 8);
Insert into GRHUM.FORMATION_PERSONNEL
   (FOR_ID, FOR_LIBELLE, FOR_COMMENTAIRE, FOR_D_OUVERTURE, FOR_D_FERMETURE, 
    D_CREATION, D_MODIFICATION, FOR_ID_PERE)
 Values
   (126, 'Prévention des risques dans l''utilisation de matériels biologiques', NULL, NULL, NULL, SYSDATE, SYSDATE, 8);
Insert into GRHUM.FORMATION_PERSONNEL
   (FOR_ID, FOR_LIBELLE, FOR_COMMENTAIRE, FOR_D_OUVERTURE, FOR_D_FERMETURE, 
    D_CREATION, D_MODIFICATION, FOR_ID_PERE)
 Values
   (127, 'Prévention des risques professionnels et responsabilités juridiques', NULL, NULL, NULL, SYSDATE, SYSDATE, 8);
Insert into GRHUM.FORMATION_PERSONNEL
   (FOR_ID, FOR_LIBELLE, FOR_COMMENTAIRE, FOR_D_OUVERTURE, FOR_D_FERMETURE, 
    D_CREATION, D_MODIFICATION, FOR_ID_PERE)
 Values
   (128, 'Vérifications techniques réglementaires dans les bâtiments universitaires', NULL, NULL, NULL, SYSDATE, SYSDATE, 8);
Insert into GRHUM.FORMATION_PERSONNEL
   (FOR_ID, FOR_LIBELLE, FOR_COMMENTAIRE, FOR_D_OUVERTURE, FOR_D_FERMETURE, 
    D_CREATION, D_MODIFICATION, FOR_ID_PERE)
 Values
   (129, 'Droit Public', NULL, NULL, NULL, SYSDATE, SYSDATE, 13);
Insert into GRHUM.FORMATION_PERSONNEL
   (FOR_ID, FOR_LIBELLE, FOR_COMMENTAIRE, FOR_D_OUVERTURE, FOR_D_FERMETURE, 
    D_CREATION, D_MODIFICATION, FOR_ID_PERE)
 Values
   (130, 'Initiation au droit administratif', NULL, NULL, NULL, SYSDATE, SYSDATE, 13);
Insert into GRHUM.FORMATION_PERSONNEL
   (FOR_ID, FOR_LIBELLE, FOR_COMMENTAIRE, FOR_D_OUVERTURE, FOR_D_FERMETURE, 
    D_CREATION, D_MODIFICATION, FOR_ID_PERE)
 Values
   (131, 'La responsabilité des agents publics', NULL, NULL, NULL, SYSDATE, SYSDATE, 13);
Insert into GRHUM.FORMATION_PERSONNEL
   (FOR_ID, FOR_LIBELLE, FOR_COMMENTAIRE, FOR_D_OUVERTURE, FOR_D_FERMETURE, 
    D_CREATION, D_MODIFICATION, FOR_ID_PERE)
 Values
   (132, 'Le contentieux administratif général', NULL, NULL, NULL, SYSDATE, SYSDATE, 13);
Insert into GRHUM.FORMATION_PERSONNEL
   (FOR_ID, FOR_LIBELLE, FOR_COMMENTAIRE, FOR_D_OUVERTURE, FOR_D_FERMETURE, 
    D_CREATION, D_MODIFICATION, FOR_ID_PERE)
 Values
   (133, 'La vie étudiante', NULL, NULL, NULL, SYSDATE, SYSDATE, 14);
Insert into GRHUM.FORMATION_PERSONNEL
   (FOR_ID, FOR_LIBELLE, FOR_COMMENTAIRE, FOR_D_OUVERTURE, FOR_D_FERMETURE, 
    D_CREATION, D_MODIFICATION, FOR_ID_PERE)
 Values
   (134, 'Accompagner l''étudiant dans sa recherche d''information', NULL, NULL, NULL, SYSDATE, SYSDATE, 14);
Insert into GRHUM.FORMATION_PERSONNEL
   (FOR_ID, FOR_LIBELLE, FOR_COMMENTAIRE, FOR_D_OUVERTURE, FOR_D_FERMETURE, 
    D_CREATION, D_MODIFICATION, FOR_ID_PERE)
 Values
   (135, 'PIE', NULL, NULL, NULL, SYSDATE, SYSDATE, 27);
Insert into GRHUM.FORMATION_PERSONNEL
   (FOR_ID, FOR_LIBELLE, FOR_COMMENTAIRE, FOR_D_OUVERTURE, FOR_D_FERMETURE, 
    D_CREATION, D_MODIFICATION, FOR_ID_PERE)
 Values
   (136, 'KIWI', NULL, NULL, NULL, SYSDATE, SYSDATE, 27);
Insert into GRHUM.FORMATION_PERSONNEL
   (FOR_ID, FOR_LIBELLE, FOR_COMMENTAIRE, FOR_D_OUVERTURE, FOR_D_FERMETURE, 
    D_CREATION, D_MODIFICATION, FOR_ID_PERE)
 Values
   (137, 'LAGAF', NULL, NULL, NULL, SYSDATE, SYSDATE, 27);
Insert into GRHUM.FORMATION_PERSONNEL
   (FOR_ID, FOR_LIBELLE, FOR_COMMENTAIRE, FOR_D_OUVERTURE, FOR_D_FERMETURE, 
    D_CREATION, D_MODIFICATION, FOR_ID_PERE)
 Values
   (138, 'COROSSOL', NULL, NULL, NULL, SYSDATE, SYSDATE, 27);
Insert into GRHUM.FORMATION_PERSONNEL
   (FOR_ID, FOR_LIBELLE, FOR_COMMENTAIRE, FOR_D_OUVERTURE, FOR_D_FERMETURE, 
    D_CREATION, D_MODIFICATION, FOR_ID_PERE)
 Values
   (139, 'CARAMBOLE', NULL, NULL, NULL, SYSDATE, SYSDATE, 27);
Insert into GRHUM.FORMATION_PERSONNEL
   (FOR_ID, FOR_LIBELLE, FOR_COMMENTAIRE, FOR_D_OUVERTURE, FOR_D_FERMETURE, 
    D_CREATION, D_MODIFICATION, FOR_ID_PERE)
 Values
   (140, 'SITUATION', NULL, NULL, NULL, SYSDATE, SYSDATE, 27);
Insert into GRHUM.FORMATION_PERSONNEL
   (FOR_ID, FOR_LIBELLE, FOR_COMMENTAIRE, FOR_D_OUVERTURE, FOR_D_FERMETURE, 
    D_CREATION, D_MODIFICATION, FOR_ID_PERE)
 Values
   (141, 'SCOL-PEDAGOGIE', NULL, NULL, NULL, SYSDATE, SYSDATE, 27);
Insert into GRHUM.FORMATION_PERSONNEL
   (FOR_ID, FOR_LIBELLE, FOR_COMMENTAIRE, FOR_D_OUVERTURE, FOR_D_FERMETURE, 
    D_CREATION, D_MODIFICATION, FOR_ID_PERE)
 Values
   (142, 'LOGICIEL PENSIONS', NULL, NULL, NULL, SYSDATE, SYSDATE, 27);
Insert into GRHUM.FORMATION_PERSONNEL
   (FOR_ID, FOR_LIBELLE, FOR_COMMENTAIRE, FOR_D_OUVERTURE, FOR_D_FERMETURE, 
    D_CREATION, D_MODIFICATION, FOR_ID_PERE)
 Values
   (143, 'Gestion du temps', NULL, NULL, NULL, SYSDATE, SYSDATE, 20);
Insert into GRHUM.FORMATION_PERSONNEL
   (FOR_ID, FOR_LIBELLE, FOR_COMMENTAIRE, FOR_D_OUVERTURE, FOR_D_FERMETURE, 
    D_CREATION, D_MODIFICATION, FOR_ID_PERE)
 Values
   (144, 'Gestion du stress', NULL, NULL, NULL, SYSDATE, SYSDATE, 20);
Insert into GRHUM.FORMATION_PERSONNEL
   (FOR_ID, FOR_LIBELLE, FOR_COMMENTAIRE, FOR_D_OUVERTURE, FOR_D_FERMETURE, 
    D_CREATION, D_MODIFICATION, FOR_ID_PERE)
 Values
   (145, 'Gérer les conflits', NULL, NULL, NULL, SYSDATE, SYSDATE, 20);
Insert into GRHUM.FORMATION_PERSONNEL
   (FOR_ID, FOR_LIBELLE, FOR_COMMENTAIRE, FOR_D_OUVERTURE, FOR_D_FERMETURE, 
    D_CREATION, D_MODIFICATION, FOR_ID_PERE)
 Values
   (146, 'Préparer sa retraite', NULL, NULL, NULL, SYSDATE, SYSDATE, 20);
Insert into GRHUM.FORMATION_PERSONNEL
   (FOR_ID, FOR_LIBELLE, FOR_COMMENTAIRE, FOR_D_OUVERTURE, FOR_D_FERMETURE, 
    D_CREATION, D_MODIFICATION, FOR_ID_PERE)
 Values
   (147, 'Prise de parole en public', NULL, NULL, NULL, SYSDATE, SYSDATE, 20);
Insert into GRHUM.FORMATION_PERSONNEL
   (FOR_ID, FOR_LIBELLE, FOR_COMMENTAIRE, FOR_D_OUVERTURE, FOR_D_FERMETURE, 
    D_CREATION, D_MODIFICATION, FOR_ID_PERE)
 Values
   (148, 'Frais de mission', NULL, NULL, NULL, SYSDATE, SYSDATE, 15);
Insert into GRHUM.FORMATION_PERSONNEL
   (FOR_ID, FOR_LIBELLE, FOR_COMMENTAIRE, FOR_D_OUVERTURE, FOR_D_FERMETURE, 
    D_CREATION, D_MODIFICATION, FOR_ID_PERE)
 Values
   (149, 'Formation COCONUTS', NULL, NULL, NULL, SYSDATE, SYSDATE, 15);
Insert into GRHUM.FORMATION_PERSONNEL
   (FOR_ID, FOR_LIBELLE, FOR_COMMENTAIRE, FOR_D_OUVERTURE, FOR_D_FERMETURE, 
    D_CREATION, D_MODIFICATION, FOR_ID_PERE)
 Values
   (150, 'Contrôle de gestion', NULL, NULL, NULL, SYSDATE, SYSDATE, 15);
Insert into GRHUM.FORMATION_PERSONNEL
   (FOR_ID, FOR_LIBELLE, FOR_COMMENTAIRE, FOR_D_OUVERTURE, FOR_D_FERMETURE, 
    D_CREATION, D_MODIFICATION, FOR_ID_PERE)
 Values
   (151, 'La LOLFsous winpaie', NULL, NULL, NULL, SYSDATE, SYSDATE, 15);
Insert into GRHUM.FORMATION_PERSONNEL
   (FOR_ID, FOR_LIBELLE, FOR_COMMENTAIRE, FOR_D_OUVERTURE, FOR_D_FERMETURE, 
    D_CREATION, D_MODIFICATION, FOR_ID_PERE)
 Values
   (152, 'Comptabilité publique', NULL, NULL, NULL, SYSDATE, SYSDATE, 15);
Insert into GRHUM.FORMATION_PERSONNEL
   (FOR_ID, FOR_LIBELLE, FOR_COMMENTAIRE, FOR_D_OUVERTURE, FOR_D_FERMETURE, 
    D_CREATION, D_MODIFICATION, FOR_ID_PERE)
 Values
   (153, 'Comptabilité analytique', NULL, NULL, NULL, SYSDATE, SYSDATE, 15);
Insert into GRHUM.FORMATION_PERSONNEL
   (FOR_ID, FOR_LIBELLE, FOR_COMMENTAIRE, FOR_D_OUVERTURE, FOR_D_FERMETURE, 
    D_CREATION, D_MODIFICATION, FOR_ID_PERE)
 Values
   (154, 'Recouvrement contentieux', NULL, NULL, NULL, SYSDATE, SYSDATE, 15);
Insert into GRHUM.FORMATION_PERSONNEL
   (FOR_ID, FOR_LIBELLE, FOR_COMMENTAIRE, FOR_D_OUVERTURE, FOR_D_FERMETURE, 
    D_CREATION, D_MODIFICATION, FOR_ID_PERE)
 Values
   (155, 'Module de comptabilité JEFYCO', NULL, NULL, NULL, SYSDATE, SYSDATE, 15);
Insert into GRHUM.FORMATION_PERSONNEL
   (FOR_ID, FOR_LIBELLE, FOR_COMMENTAIRE, FOR_D_OUVERTURE, FOR_D_FERMETURE, 
    D_CREATION, D_MODIFICATION, FOR_ID_PERE)
 Values
   (156, 'Gestion financière d''un EPSCP-LOLF', NULL, NULL, NULL, SYSDATE, SYSDATE, 15);
Insert into GRHUM.FORMATION_PERSONNEL
   (FOR_ID, FOR_LIBELLE, FOR_COMMENTAIRE, FOR_D_OUVERTURE, FOR_D_FERMETURE, 
    D_CREATION, D_MODIFICATION, FOR_ID_PERE)
 Values
   (157, 'Perfectionnement en comptabilité générale', NULL, NULL, NULL, SYSDATE, SYSDATE, 15);
Insert into GRHUM.FORMATION_PERSONNEL
   (FOR_ID, FOR_LIBELLE, FOR_COMMENTAIRE, FOR_D_OUVERTURE, FOR_D_FERMETURE, 
    D_CREATION, D_MODIFICATION, FOR_ID_PERE)
 Values
   (158, 'La pratique de l''inventaire dans les EPSCP', NULL, NULL, NULL, SYSDATE, SYSDATE, 15);
Insert into GRHUM.FORMATION_PERSONNEL
   (FOR_ID, FOR_LIBELLE, FOR_COMMENTAIRE, FOR_D_OUVERTURE, FOR_D_FERMETURE, 
    D_CREATION, D_MODIFICATION, FOR_ID_PERE)
 Values
   (159, 'Système d''information et des comptabilités publiques', NULL, NULL, NULL, SYSDATE, SYSDATE, 15);
Insert into GRHUM.FORMATION_PERSONNEL
   (FOR_ID, FOR_LIBELLE, FOR_COMMENTAIRE, FOR_D_OUVERTURE, FOR_D_FERMETURE, 
    D_CREATION, D_MODIFICATION, FOR_ID_PERE)
 Values
   (160, 'Mise en oeuvre de la loi organique relative aux lois de finances (LOLF)', NULL, NULL, NULL, SYSDATE, SYSDATE, 15);
Insert into GRHUM.FORMATION_PERSONNEL
   (FOR_ID, FOR_LIBELLE, FOR_COMMENTAIRE, FOR_D_OUVERTURE, FOR_D_FERMETURE, 
    D_CREATION, D_MODIFICATION, FOR_ID_PERE)
 Values
   (161, 'entretien batiment', NULL, NULL, NULL, SYSDATE, SYSDATE, 2);
Insert into GRHUM.FORMATION_PERSONNEL
   (FOR_ID, FOR_LIBELLE, FOR_COMMENTAIRE, FOR_D_OUVERTURE, FOR_D_FERMETURE, 
    D_CREATION, D_MODIFICATION, FOR_ID_PERE)
 Values
   (162, 'Entretien des locaux', NULL, NULL, NULL, SYSDATE, SYSDATE, 2);
Insert into GRHUM.FORMATION_PERSONNEL
   (FOR_ID, FOR_LIBELLE, FOR_COMMENTAIRE, FOR_D_OUVERTURE, FOR_D_FERMETURE, 
    D_CREATION, D_MODIFICATION, FOR_ID_PERE)
 Values
   (163, 'gestion du patrimoine ', NULL, NULL, NULL, SYSDATE, SYSDATE, 2);
Insert into GRHUM.FORMATION_PERSONNEL
   (FOR_ID, FOR_LIBELLE, FOR_COMMENTAIRE, FOR_D_OUVERTURE, FOR_D_FERMETURE, 
    D_CREATION, D_MODIFICATION, FOR_ID_PERE)
 Values
   (164, 'Domanialité et valorisation', NULL, NULL, NULL, SYSDATE, SYSDATE, 2);
Insert into GRHUM.FORMATION_PERSONNEL
   (FOR_ID, FOR_LIBELLE, FOR_COMMENTAIRE, FOR_D_OUVERTURE, FOR_D_FERMETURE, 
    D_CREATION, D_MODIFICATION, FOR_ID_PERE)
 Values
   (165, 'CAO-DAO avec AUTOCAD - Niveau 1', NULL, NULL, NULL, SYSDATE, SYSDATE, 2);
Insert into GRHUM.FORMATION_PERSONNEL
   (FOR_ID, FOR_LIBELLE, FOR_COMMENTAIRE, FOR_D_OUVERTURE, FOR_D_FERMETURE, 
    D_CREATION, D_MODIFICATION, FOR_ID_PERE)
 Values
   (166, 'CAO-DAO avec AUTOCAD - Niveau 2', NULL, NULL, NULL, SYSDATE, SYSDATE, 2);
Insert into GRHUM.FORMATION_PERSONNEL
   (FOR_ID, FOR_LIBELLE, FOR_COMMENTAIRE, FOR_D_OUVERTURE, FOR_D_FERMETURE, 
    D_CREATION, D_MODIFICATION, FOR_ID_PERE)
 Values
   (167, 'Maintenance de bâtiments collectifs', NULL, NULL, NULL, SYSDATE, SYSDATE, 2);
Insert into GRHUM.FORMATION_PERSONNEL
   (FOR_ID, FOR_LIBELLE, FOR_COMMENTAIRE, FOR_D_OUVERTURE, FOR_D_FERMETURE, 
    D_CREATION, D_MODIFICATION, FOR_ID_PERE)
 Values
   (168, 'La gestion du patrimoine dans les universités', NULL, NULL, NULL, SYSDATE, SYSDATE, 2);
Insert into GRHUM.FORMATION_PERSONNEL
   (FOR_ID, FOR_LIBELLE, FOR_COMMENTAIRE, FOR_D_OUVERTURE, FOR_D_FERMETURE, 
    D_CREATION, D_MODIFICATION, FOR_ID_PERE)
 Values
   (169, 'Electricité Niveau 2 - Maintenance en électricité', NULL, NULL, NULL, SYSDATE, SYSDATE, 2);
Insert into GRHUM.FORMATION_PERSONNEL
   (FOR_ID, FOR_LIBELLE, FOR_COMMENTAIRE, FOR_D_OUVERTURE, FOR_D_FERMETURE, 
    D_CREATION, D_MODIFICATION, FOR_ID_PERE)
 Values
   (170, 'compagnonage en électricité formation de plombier, chauffagiste', NULL, NULL, NULL, SYSDATE, SYSDATE, 2);
Insert into GRHUM.FORMATION_PERSONNEL
   (FOR_ID, FOR_LIBELLE, FOR_COMMENTAIRE, FOR_D_OUVERTURE, FOR_D_FERMETURE, 
    D_CREATION, D_MODIFICATION, FOR_ID_PERE)
 Values
   (171, 'Formations sur les métiers du bâtiment (plomberie, électricité etc...)', NULL, NULL, NULL, SYSDATE, SYSDATE, 2);
Insert into GRHUM.FORMATION_PERSONNEL
   (FOR_ID, FOR_LIBELLE, FOR_COMMENTAIRE, FOR_D_OUVERTURE, FOR_D_FERMETURE, 
    D_CREATION, D_MODIFICATION, FOR_ID_PERE)
 Values
   (172, 'Performances énergétiques appliquées aux bâtiments de l''Enseignement supérieur', NULL, NULL, NULL, SYSDATE, SYSDATE, 2);
Insert into GRHUM.FORMATION_PERSONNEL
   (FOR_ID, FOR_LIBELLE, FOR_COMMENTAIRE, FOR_D_OUVERTURE, FOR_D_FERMETURE, 
    D_CREATION, D_MODIFICATION, FOR_ID_PERE)
 Values
   (173, 'linux', NULL, NULL, NULL, SYSDATE, SYSDATE, 28);
Insert into GRHUM.FORMATION_PERSONNEL
   (FOR_ID, FOR_LIBELLE, FOR_COMMENTAIRE, FOR_D_OUVERTURE, FOR_D_FERMETURE, 
    D_CREATION, D_MODIFICATION, FOR_ID_PERE)
 Values
   (174, 'Oracle', NULL, NULL, NULL, SYSDATE, SYSDATE, 28);
Insert into GRHUM.FORMATION_PERSONNEL
   (FOR_ID, FOR_LIBELLE, FOR_COMMENTAIRE, FOR_D_OUVERTURE, FOR_D_FERMETURE, 
    D_CREATION, D_MODIFICATION, FOR_ID_PERE)
 Values
   (175, 'Réseau', NULL, NULL, NULL, SYSDATE, SYSDATE, 28);
Insert into GRHUM.FORMATION_PERSONNEL
   (FOR_ID, FOR_LIBELLE, FOR_COMMENTAIRE, FOR_D_OUVERTURE, FOR_D_FERMETURE, 
    D_CREATION, D_MODIFICATION, FOR_ID_PERE)
 Values
   (176, 'Mac OSX', NULL, NULL, NULL, SYSDATE, SYSDATE, 28);
Insert into GRHUM.FORMATION_PERSONNEL
   (FOR_ID, FOR_LIBELLE, FOR_COMMENTAIRE, FOR_D_OUVERTURE, FOR_D_FERMETURE, 
    D_CREATION, D_MODIFICATION, FOR_ID_PERE)
 Values
   (177, 'réseaux', NULL, NULL, NULL, SYSDATE, SYSDATE, 28);
Insert into GRHUM.FORMATION_PERSONNEL
   (FOR_ID, FOR_LIBELLE, FOR_COMMENTAIRE, FOR_D_OUVERTURE, FOR_D_FERMETURE, 
    D_CREATION, D_MODIFICATION, FOR_ID_PERE)
 Values
   (178, 'Voix sur IP', NULL, NULL, NULL, SYSDATE, SYSDATE, 28);
Insert into GRHUM.FORMATION_PERSONNEL
   (FOR_ID, FOR_LIBELLE, FOR_COMMENTAIRE, FOR_D_OUVERTURE, FOR_D_FERMETURE, 
    D_CREATION, D_MODIFICATION, FOR_ID_PERE)
 Values
   (179, 'Langage Java', NULL, NULL, NULL, SYSDATE, SYSDATE, 28);
Insert into GRHUM.FORMATION_PERSONNEL
   (FOR_ID, FOR_LIBELLE, FOR_COMMENTAIRE, FOR_D_OUVERTURE, FOR_D_FERMETURE, 
    D_CREATION, D_MODIFICATION, FOR_ID_PERE)
 Values
   (180, 'Développement', NULL, NULL, NULL, SYSDATE, SYSDATE, 28);
Insert into GRHUM.FORMATION_PERSONNEL
   (FOR_ID, FOR_LIBELLE, FOR_COMMENTAIRE, FOR_D_OUVERTURE, FOR_D_FERMETURE, 
    D_CREATION, D_MODIFICATION, FOR_ID_PERE)
 Values
   (181, 'Windows serveur', NULL, NULL, NULL, SYSDATE, SYSDATE, 28);
Insert into GRHUM.FORMATION_PERSONNEL
   (FOR_ID, FOR_LIBELLE, FOR_COMMENTAIRE, FOR_D_OUVERTURE, FOR_D_FERMETURE, 
    D_CREATION, D_MODIFICATION, FOR_ID_PERE)
 Values
   (182, 'commandes UNIX ', NULL, NULL, NULL, SYSDATE, SYSDATE, 28);
Insert into GRHUM.FORMATION_PERSONNEL
   (FOR_ID, FOR_LIBELLE, FOR_COMMENTAIRE, FOR_D_OUVERTURE, FOR_D_FERMETURE, 
    D_CREATION, D_MODIFICATION, FOR_ID_PERE)
 Values
   (183, 'Active Directory', NULL, NULL, NULL, SYSDATE, SYSDATE, 28);
Insert into GRHUM.FORMATION_PERSONNEL
   (FOR_ID, FOR_LIBELLE, FOR_COMMENTAIRE, FOR_D_OUVERTURE, FOR_D_FERMETURE, 
    D_CREATION, D_MODIFICATION, FOR_ID_PERE)
 Values
   (184, 'Téléphonie sur IP', NULL, NULL, NULL, SYSDATE, SYSDATE, 28);
Insert into GRHUM.FORMATION_PERSONNEL
   (FOR_ID, FOR_LIBELLE, FOR_COMMENTAIRE, FOR_D_OUVERTURE, FOR_D_FERMETURE, 
    D_CREATION, D_MODIFICATION, FOR_ID_PERE)
 Values
   (185, 'Script réseau PERL', NULL, NULL, NULL, SYSDATE, SYSDATE, 28);
Insert into GRHUM.FORMATION_PERSONNEL
   (FOR_ID, FOR_LIBELLE, FOR_COMMENTAIRE, FOR_D_OUVERTURE, FOR_D_FERMETURE, 
    D_CREATION, D_MODIFICATION, FOR_ID_PERE)
 Values
   (186, 'Mac OS X Essentials', NULL, NULL, NULL, SYSDATE, SYSDATE, 28);
Insert into GRHUM.FORMATION_PERSONNEL
   (FOR_ID, FOR_LIBELLE, FOR_COMMENTAIRE, FOR_D_OUVERTURE, FOR_D_FERMETURE, 
    D_CREATION, D_MODIFICATION, FOR_ID_PERE)
 Values
   (187, 'création de scripts', NULL, NULL, NULL, SYSDATE, SYSDATE, 28);
Insert into GRHUM.FORMATION_PERSONNEL
   (FOR_ID, FOR_LIBELLE, FOR_COMMENTAIRE, FOR_D_OUVERTURE, FOR_D_FERMETURE, 
    D_CREATION, D_MODIFICATION, FOR_ID_PERE)
 Values
   (188, 'langages de scripts', NULL, NULL, NULL, SYSDATE, SYSDATE, 28);
Insert into GRHUM.FORMATION_PERSONNEL
   (FOR_ID, FOR_LIBELLE, FOR_COMMENTAIRE, FOR_D_OUVERTURE, FOR_D_FERMETURE, 
    D_CREATION, D_MODIFICATION, FOR_ID_PERE)
 Values
   (189, 'virtualisation d''OS', NULL, NULL, NULL, SYSDATE, SYSDATE, 28);
Insert into GRHUM.FORMATION_PERSONNEL
   (FOR_ID, FOR_LIBELLE, FOR_COMMENTAIRE, FOR_D_OUVERTURE, FOR_D_FERMETURE, 
    D_CREATION, D_MODIFICATION, FOR_ID_PERE)
 Values
   (190, 'Oracle et ses outils', NULL, NULL, NULL, SYSDATE, SYSDATE, 28);
Insert into GRHUM.FORMATION_PERSONNEL
   (FOR_ID, FOR_LIBELLE, FOR_COMMENTAIRE, FOR_D_OUVERTURE, FOR_D_FERMETURE, 
    D_CREATION, D_MODIFICATION, FOR_ID_PERE)
 Values
   (191, 'Perfectionnement SQL', NULL, NULL, NULL, SYSDATE, SYSDATE, 28);
Insert into GRHUM.FORMATION_PERSONNEL
   (FOR_ID, FOR_LIBELLE, FOR_COMMENTAIRE, FOR_D_OUVERTURE, FOR_D_FERMETURE, 
    D_CREATION, D_MODIFICATION, FOR_ID_PERE)
 Values
   (192, 'Stockage,VMWare, ...', NULL, NULL, NULL, SYSDATE, SYSDATE, 28);
Insert into GRHUM.FORMATION_PERSONNEL
   (FOR_ID, FOR_LIBELLE, FOR_COMMENTAIRE, FOR_D_OUVERTURE, FOR_D_FERMETURE, 
    D_CREATION, D_MODIFICATION, FOR_ID_PERE)
 Values
   (193, 'Démarche qualité ITIL', NULL, NULL, NULL, SYSDATE, SYSDATE, 28);
Insert into GRHUM.FORMATION_PERSONNEL
   (FOR_ID, FOR_LIBELLE, FOR_COMMENTAIRE, FOR_D_OUVERTURE, FOR_D_FERMETURE, 
    D_CREATION, D_MODIFICATION, FOR_ID_PERE)
 Values
   (194, 'Mac osx (déploiement)', NULL, NULL, NULL, SYSDATE, SYSDATE, 28);
Insert into GRHUM.FORMATION_PERSONNEL
   (FOR_ID, FOR_LIBELLE, FOR_COMMENTAIRE, FOR_D_OUVERTURE, FOR_D_FERMETURE, 
    D_CREATION, D_MODIFICATION, FOR_ID_PERE)
 Values
   (195, 'Linux (aspects serveur)', NULL, NULL, NULL, SYSDATE, SYSDATE, 28);
Insert into GRHUM.FORMATION_PERSONNEL
   (FOR_ID, FOR_LIBELLE, FOR_COMMENTAIRE, FOR_D_OUVERTURE, FOR_D_FERMETURE, 
    D_CREATION, D_MODIFICATION, FOR_ID_PERE)
 Values
   (196, 'AJAX pour application Web', NULL, NULL, NULL, SYSDATE, SYSDATE, 28);
Insert into GRHUM.FORMATION_PERSONNEL
   (FOR_ID, FOR_LIBELLE, FOR_COMMENTAIRE, FOR_D_OUVERTURE, FOR_D_FERMETURE, 
    D_CREATION, D_MODIFICATION, FOR_ID_PERE)
 Values
   (197, 'Expertise administrateur BO', NULL, NULL, NULL, SYSDATE, SYSDATE, 28);
Insert into GRHUM.FORMATION_PERSONNEL
   (FOR_ID, FOR_LIBELLE, FOR_COMMENTAIRE, FOR_D_OUVERTURE, FOR_D_FERMETURE, 
    D_CREATION, D_MODIFICATION, FOR_ID_PERE)
 Values
   (198, 'Administration de switch HP ', NULL, NULL, NULL, SYSDATE, SYSDATE, 28);
Insert into GRHUM.FORMATION_PERSONNEL
   (FOR_ID, FOR_LIBELLE, FOR_COMMENTAIRE, FOR_D_OUVERTURE, FOR_D_FERMETURE, 
    D_CREATION, D_MODIFICATION, FOR_ID_PERE)
 Values
   (199, 'Formation Apple, déploiement', NULL, NULL, NULL, SYSDATE, SYSDATE, 28);
Insert into GRHUM.FORMATION_PERSONNEL
   (FOR_ID, FOR_LIBELLE, FOR_COMMENTAIRE, FOR_D_OUVERTURE, FOR_D_FERMETURE, 
    D_CREATION, D_MODIFICATION, FOR_ID_PERE)
 Values
   (200, 'formation Linux et/ou MacOSX', NULL, NULL, NULL, SYSDATE, SYSDATE, 28);
Insert into GRHUM.FORMATION_PERSONNEL
   (FOR_ID, FOR_LIBELLE, FOR_COMMENTAIRE, FOR_D_OUVERTURE, FOR_D_FERMETURE, 
    D_CREATION, D_MODIFICATION, FOR_ID_PERE)
 Values
   (201, 'Sur le logiciel Deploy Studio ', NULL, NULL, NULL, SYSDATE, SYSDATE, 28);
Insert into GRHUM.FORMATION_PERSONNEL
   (FOR_ID, FOR_LIBELLE, FOR_COMMENTAIRE, FOR_D_OUVERTURE, FOR_D_FERMETURE, 
    D_CREATION, D_MODIFICATION, FOR_ID_PERE)
 Values
   (202, 'Administration du système Linux', NULL, NULL, NULL, SYSDATE, SYSDATE, 28);
Insert into GRHUM.FORMATION_PERSONNEL
   (FOR_ID, FOR_LIBELLE, FOR_COMMENTAIRE, FOR_D_OUVERTURE, FOR_D_FERMETURE, 
    D_CREATION, D_MODIFICATION, FOR_ID_PERE)
 Values
   (203, 'Sécurité des systèmes et réseaux', NULL, NULL, NULL, SYSDATE, SYSDATE, 28);
Insert into GRHUM.FORMATION_PERSONNEL
   (FOR_ID, FOR_LIBELLE, FOR_COMMENTAIRE, FOR_D_OUVERTURE, FOR_D_FERMETURE, 
    D_CREATION, D_MODIFICATION, FOR_ID_PERE)
 Values
   (204, 'environnement mac et système MacOSX', NULL, NULL, NULL, SYSDATE, SYSDATE, 28);
Insert into GRHUM.FORMATION_PERSONNEL
   (FOR_ID, FOR_LIBELLE, FOR_COMMENTAIRE, FOR_D_OUVERTURE, FOR_D_FERMETURE, 
    D_CREATION, D_MODIFICATION, FOR_ID_PERE)
 Values
   (205, 'perfectionnement en base de données', NULL, NULL, NULL, SYSDATE, SYSDATE, 28);
Insert into GRHUM.FORMATION_PERSONNEL
   (FOR_ID, FOR_LIBELLE, FOR_COMMENTAIRE, FOR_D_OUVERTURE, FOR_D_FERMETURE, 
    D_CREATION, D_MODIFICATION, FOR_ID_PERE)
 Values
   (206, 'logiciels et techniques de déploiement', NULL, NULL, NULL, SYSDATE, SYSDATE, 28);
Insert into GRHUM.FORMATION_PERSONNEL
   (FOR_ID, FOR_LIBELLE, FOR_COMMENTAIRE, FOR_D_OUVERTURE, FOR_D_FERMETURE, 
    D_CREATION, D_MODIFICATION, FOR_ID_PERE)
 Values
   (207, 'Formation d''approfondissement WebObjects ', NULL, NULL, NULL, SYSDATE, SYSDATE, 28);
Insert into GRHUM.FORMATION_PERSONNEL
   (FOR_ID, FOR_LIBELLE, FOR_COMMENTAIRE, FOR_D_OUVERTURE, FOR_D_FERMETURE, 
    D_CREATION, D_MODIFICATION, FOR_ID_PERE)
 Values
   (208, 'Mise à niveau des fonctionnalités Oracle 11g', NULL, NULL, NULL, SYSDATE, SYSDATE, 28);
Insert into GRHUM.FORMATION_PERSONNEL
   (FOR_ID, FOR_LIBELLE, FOR_COMMENTAIRE, FOR_D_OUVERTURE, FOR_D_FERMETURE, 
    D_CREATION, D_MODIFICATION, FOR_ID_PERE)
 Values
   (209, 'Technique d''exploitation de Base de Données.', NULL, NULL, NULL, SYSDATE, SYSDATE, 28);
Insert into GRHUM.FORMATION_PERSONNEL
   (FOR_ID, FOR_LIBELLE, FOR_COMMENTAIRE, FOR_D_OUVERTURE, FOR_D_FERMETURE, 
    D_CREATION, D_MODIFICATION, FOR_ID_PERE)
 Values
   (210, 'VMWare Serveur (Administration - Virtualisation)', NULL, NULL, NULL, SYSDATE, SYSDATE, 28);
Insert into GRHUM.FORMATION_PERSONNEL
   (FOR_ID, FOR_LIBELLE, FOR_COMMENTAIRE, FOR_D_OUVERTURE, FOR_D_FERMETURE, 
    D_CREATION, D_MODIFICATION, FOR_ID_PERE)
 Values
   (211, 'Formation sur la modélisation BDD (Base De Données)', NULL, NULL, NULL, SYSDATE, SYSDATE, 28);
Insert into GRHUM.FORMATION_PERSONNEL
   (FOR_ID, FOR_LIBELLE, FOR_COMMENTAIRE, FOR_D_OUVERTURE, FOR_D_FERMETURE, 
    D_CREATION, D_MODIFICATION, FOR_ID_PERE)
 Values
   (212, 'métrologie et supervision des réseaux informatiques', NULL, NULL, NULL, SYSDATE, SYSDATE, 28);
Insert into GRHUM.FORMATION_PERSONNEL
   (FOR_ID, FOR_LIBELLE, FOR_COMMENTAIRE, FOR_D_OUVERTURE, FOR_D_FERMETURE, 
    D_CREATION, D_MODIFICATION, FOR_ID_PERE)
 Values
   (213, 'Réseaux de l''Enseignement supérieur et de la recherche', NULL, NULL, NULL, SYSDATE, SYSDATE, 28);
Insert into GRHUM.FORMATION_PERSONNEL
   (FOR_ID, FOR_LIBELLE, FOR_COMMENTAIRE, FOR_D_OUVERTURE, FOR_D_FERMETURE, 
    D_CREATION, D_MODIFICATION, FOR_ID_PERE)
 Values
   (214, 'développement Web Object AJAX avec l''association Cocktail', NULL, NULL, NULL, SYSDATE, SYSDATE, 28);
Insert into GRHUM.FORMATION_PERSONNEL
   (FOR_ID, FOR_LIBELLE, FOR_COMMENTAIRE, FOR_D_OUVERTURE, FOR_D_FERMETURE, 
    D_CREATION, D_MODIFICATION, FOR_ID_PERE)
 Values
   (215, 'développement web (php, javascript, ajax, xhtml, asp etc ...)', NULL, NULL, NULL, SYSDATE, SYSDATE, 28);
Insert into GRHUM.FORMATION_PERSONNEL
   (FOR_ID, FOR_LIBELLE, FOR_COMMENTAIRE, FOR_D_OUVERTURE, FOR_D_FERMETURE, 
    D_CREATION, D_MODIFICATION, FOR_ID_PERE)
 Values
   (216, 'Appareillage DMA', NULL, NULL, NULL, SYSDATE, SYSDATE, 10);
Insert into GRHUM.FORMATION_PERSONNEL
   (FOR_ID, FOR_LIBELLE, FOR_COMMENTAIRE, FOR_D_OUVERTURE, FOR_D_FERMETURE, 
    D_CREATION, D_MODIFICATION, FOR_ID_PERE)
 Values
   (217, 'Lithopréparateur', NULL, NULL, NULL, SYSDATE, SYSDATE, 10);
Insert into GRHUM.FORMATION_PERSONNEL
   (FOR_ID, FOR_LIBELLE, FOR_COMMENTAIRE, FOR_D_OUVERTURE, FOR_D_FERMETURE, 
    D_CREATION, D_MODIFICATION, FOR_ID_PERE)
 Values
   (218, 'Litholaméleurs Lithobroyeurs', NULL, NULL, NULL, SYSDATE, SYSDATE, 10);
Insert into GRHUM.FORMATION_PERSONNEL
   (FOR_ID, FOR_LIBELLE, FOR_COMMENTAIRE, FOR_D_OUVERTURE, FOR_D_FERMETURE, 
    D_CREATION, D_MODIFICATION, FOR_ID_PERE)
 Values
   (219, 'Séquençage automatique d''ADN', NULL, NULL, NULL, SYSDATE, SYSDATE, 10);
Insert into GRHUM.FORMATION_PERSONNEL
   (FOR_ID, FOR_LIBELLE, FOR_COMMENTAIRE, FOR_D_OUVERTURE, FOR_D_FERMETURE, 
    D_CREATION, D_MODIFICATION, FOR_ID_PERE)
 Values
   (220, 'Initiation bonnes pratiques de laboratoire', NULL, NULL, NULL, SYSDATE, SYSDATE, 10);
Insert into GRHUM.FORMATION_PERSONNEL
   (FOR_ID, FOR_LIBELLE, FOR_COMMENTAIRE, FOR_D_OUVERTURE, FOR_D_FERMETURE, 
    D_CREATION, D_MODIFICATION, FOR_ID_PERE)
 Values
   (221, 'La recherche dans l''enseignement supérieur', NULL, NULL, NULL, SYSDATE, SYSDATE, 10);
Insert into GRHUM.FORMATION_PERSONNEL
   (FOR_ID, FOR_LIBELLE, FOR_COMMENTAIRE, FOR_D_OUVERTURE, FOR_D_FERMETURE, 
    D_CREATION, D_MODIFICATION, FOR_ID_PERE)
 Values
   (222, 'Préparation d''échantillons métallographiques', NULL, NULL, NULL, SYSDATE, SYSDATE, 10);
Insert into GRHUM.FORMATION_PERSONNEL
   (FOR_ID, FOR_LIBELLE, FOR_COMMENTAIRE, FOR_D_OUVERTURE, FOR_D_FERMETURE, 
    D_CREATION, D_MODIFICATION, FOR_ID_PERE)
 Values
   (223, 'LABVIEW AVANCE - Acquisition de données sur PC', NULL, NULL, NULL, SYSDATE, SYSDATE, 10);
Insert into GRHUM.FORMATION_PERSONNEL
   (FOR_ID, FOR_LIBELLE, FOR_COMMENTAIRE, FOR_D_OUVERTURE, FOR_D_FERMETURE, 
    D_CREATION, D_MODIFICATION, FOR_ID_PERE)
 Values
   (224, 'Biologie moléculaire - techniques PCR et clônage', NULL, NULL, NULL, SYSDATE, SYSDATE, 10);
Insert into GRHUM.FORMATION_PERSONNEL
   (FOR_ID, FOR_LIBELLE, FOR_COMMENTAIRE, FOR_D_OUVERTURE, FOR_D_FERMETURE, 
    D_CREATION, D_MODIFICATION, FOR_ID_PERE)
 Values
   (225, 'MICROSCOPIE ELECTRONIQUE - PREPARATION D''ECHANTILLONS', NULL, NULL, NULL, SYSDATE, SYSDATE, 10);
Insert into GRHUM.FORMATION_PERSONNEL
   (FOR_ID, FOR_LIBELLE, FOR_COMMENTAIRE, FOR_D_OUVERTURE, FOR_D_FERMETURE, 
    D_CREATION, D_MODIFICATION, FOR_ID_PERE)
 Values
   (226, 'Systèmes d''Information Géographique & Bases de données', NULL, NULL, NULL, SYSDATE, SYSDATE, 10);
Insert into GRHUM.FORMATION_PERSONNEL
   (FOR_ID, FOR_LIBELLE, FOR_COMMENTAIRE, FOR_D_OUVERTURE, FOR_D_FERMETURE, 
    D_CREATION, D_MODIFICATION, FOR_ID_PERE)
 Values
   (227, 'Perfectionnement en spectrométrie d''émission plasma ICP', NULL, NULL, NULL, SYSDATE, SYSDATE, 10);
Insert into GRHUM.FORMATION_PERSONNEL
   (FOR_ID, FOR_LIBELLE, FOR_COMMENTAIRE, FOR_D_OUVERTURE, FOR_D_FERMETURE, 
    D_CREATION, D_MODIFICATION, FOR_ID_PERE)
 Values
   (228, 'Perfectionnement à Labview - acquisition de données sur PC', NULL, NULL, NULL, SYSDATE, SYSDATE, 10);
Insert into GRHUM.FORMATION_PERSONNEL
   (FOR_ID, FOR_LIBELLE, FOR_COMMENTAIRE, FOR_D_OUVERTURE, FOR_D_FERMETURE, 
    D_CREATION, D_MODIFICATION, FOR_ID_PERE)
 Values
   (229, 'Microscopie électronique à balayage et microanalyse X (MEB)', NULL, NULL, NULL, SYSDATE, SYSDATE, 10);
Insert into GRHUM.FORMATION_PERSONNEL
   (FOR_ID, FOR_LIBELLE, FOR_COMMENTAIRE, FOR_D_OUVERTURE, FOR_D_FERMETURE, 
    D_CREATION, D_MODIFICATION, FOR_ID_PERE)
 Values
   (230, 'Initiation à Labview Version 8 - Acquisition de données sur PC', NULL, NULL, NULL, SYSDATE, SYSDATE, 10);
Insert into GRHUM.FORMATION_PERSONNEL
   (FOR_ID, FOR_LIBELLE, FOR_COMMENTAIRE, FOR_D_OUVERTURE, FOR_D_FERMETURE, 
    D_CREATION, D_MODIFICATION, FOR_ID_PERE)
 Values
   (231, '(M.E.T.) Microscopie électronique à transmission et microanalyse X', NULL, NULL, NULL, SYSDATE, SYSDATE, 10);
Insert into GRHUM.FORMATION_PERSONNEL
   (FOR_ID, FOR_LIBELLE, FOR_COMMENTAIRE, FOR_D_OUVERTURE, FOR_D_FERMETURE, 
    D_CREATION, D_MODIFICATION, FOR_ID_PERE)
 Values
   (232, 'Perfectionnement et échanges des connaissances en lithopréparation', NULL, NULL, NULL, SYSDATE, SYSDATE, 10);
Insert into GRHUM.FORMATION_PERSONNEL
   (FOR_ID, FOR_LIBELLE, FOR_COMMENTAIRE, FOR_D_OUVERTURE, FOR_D_FERMETURE, 
    D_CREATION, D_MODIFICATION, FOR_ID_PERE)
 Values
   (233, 'Initiation à la résonance magnétique nucléaire du proton et du carbone (RMN)', NULL, NULL, NULL, SYSDATE, SYSDATE, 10);
Insert into GRHUM.FORMATION_PERSONNEL
   (FOR_ID, FOR_LIBELLE, FOR_COMMENTAIRE, FOR_D_OUVERTURE, FOR_D_FERMETURE, 
    D_CREATION, D_MODIFICATION, FOR_ID_PERE)
 Values
   (234, 'Note administrative', NULL, NULL, NULL, SYSDATE, SYSDATE, 33);
Insert into GRHUM.FORMATION_PERSONNEL
   (FOR_ID, FOR_LIBELLE, FOR_COMMENTAIRE, FOR_D_OUVERTURE, FOR_D_FERMETURE, 
    D_CREATION, D_MODIFICATION, FOR_ID_PERE)
 Values
   (235, 'Préparation APAENES', NULL, NULL, NULL, SYSDATE, SYSDATE, 33);
Insert into GRHUM.FORMATION_PERSONNEL
   (FOR_ID, FOR_LIBELLE, FOR_COMMENTAIRE, FOR_D_OUVERTURE, FOR_D_FERMETURE, 
    D_CREATION, D_MODIFICATION, FOR_ID_PERE)
 Values
   (236, 'Magasinier spécialisé', NULL, NULL, NULL, SYSDATE, SYSDATE, 33);
Insert into GRHUM.FORMATION_PERSONNEL
   (FOR_ID, FOR_LIBELLE, FOR_COMMENTAIRE, FOR_D_OUVERTURE, FOR_D_FERMETURE, 
    D_CREATION, D_MODIFICATION, FOR_ID_PERE)
 Values
   (237, 'Auxiliaire de bibliothèque', NULL, NULL, NULL, SYSDATE, SYSDATE, 33);
Insert into GRHUM.FORMATION_PERSONNEL
   (FOR_ID, FOR_LIBELLE, FOR_COMMENTAIRE, FOR_D_OUVERTURE, FOR_D_FERMETURE, 
    D_CREATION, D_MODIFICATION, FOR_ID_PERE)
 Values
   (238, 'Préparation concours SAENES', NULL, NULL, NULL, SYSDATE, SYSDATE, 33);
Insert into GRHUM.FORMATION_PERSONNEL
   (FOR_ID, FOR_LIBELLE, FOR_COMMENTAIRE, FOR_D_OUVERTURE, FOR_D_FERMETURE, 
    D_CREATION, D_MODIFICATION, FOR_ID_PERE)
 Values
   (239, 'Rédaction d''un rapport d''activité', NULL, NULL, NULL, SYSDATE, SYSDATE, 33);
Insert into GRHUM.FORMATION_PERSONNEL
   (FOR_ID, FOR_LIBELLE, FOR_COMMENTAIRE, FOR_D_OUVERTURE, FOR_D_FERMETURE, 
    D_CREATION, D_MODIFICATION, FOR_ID_PERE)
 Values
   (240, 'Préparation aux concours de catégorie B', NULL, NULL, NULL, SYSDATE, SYSDATE, 33);
Insert into GRHUM.FORMATION_PERSONNEL
   (FOR_ID, FOR_LIBELLE, FOR_COMMENTAIRE, FOR_D_OUVERTURE, FOR_D_FERMETURE, 
    D_CREATION, D_MODIFICATION, FOR_ID_PERE)
 Values
   (241, 'Préparation SAENES Classe exceptionnelle', NULL, NULL, NULL, SYSDATE, SYSDATE, 33);
Insert into GRHUM.FORMATION_PERSONNEL
   (FOR_ID, FOR_LIBELLE, FOR_COMMENTAIRE, FOR_D_OUVERTURE, FOR_D_FERMETURE, 
    D_CREATION, D_MODIFICATION, FOR_ID_PERE)
 Values
   (242, 'Préparation concours Adjoint Administratif', NULL, NULL, NULL, SYSDATE, SYSDATE, 33);
Insert into GRHUM.FORMATION_PERSONNEL
   (FOR_ID, FOR_LIBELLE, FOR_COMMENTAIRE, FOR_D_OUVERTURE, FOR_D_FERMETURE, 
    D_CREATION, D_MODIFICATION, FOR_ID_PERE)
 Values
   (243, 'Préparation au concours de magasinier principal 2ème classe', NULL, NULL, NULL, SYSDATE, SYSDATE, 33);
Insert into GRHUM.FORMATION_PERSONNEL
   (FOR_ID, FOR_LIBELLE, FOR_COMMENTAIRE, FOR_D_OUVERTURE, FOR_D_FERMETURE, 
    D_CREATION, D_MODIFICATION, FOR_ID_PERE)
 Values
   (244, 'Préparation à l''oral des concours et examens professionnels', NULL, NULL, NULL, SYSDATE, SYSDATE, 33);
Insert into GRHUM.FORMATION_PERSONNEL
   (FOR_ID, FOR_LIBELLE, FOR_COMMENTAIRE, FOR_D_OUVERTURE, FOR_D_FERMETURE, 
    D_CREATION, D_MODIFICATION, FOR_ID_PERE)
 Values
   (245, 'Formation de formateur', NULL, NULL, NULL, SYSDATE, SYSDATE, 21);
Insert into GRHUM.FORMATION_PERSONNEL
   (FOR_ID, FOR_LIBELLE, FOR_COMMENTAIRE, FOR_D_OUVERTURE, FOR_D_FERMETURE, 
    D_CREATION, D_MODIFICATION, FOR_ID_PERE)
 Values
   (246, 'Organiser une formation', NULL, NULL, NULL, SYSDATE, SYSDATE, 21);
Insert into GRHUM.FORMATION_PERSONNEL
   (FOR_ID, FOR_LIBELLE, FOR_COMMENTAIRE, FOR_D_OUVERTURE, FOR_D_FERMETURE, 
    D_CREATION, D_MODIFICATION, FOR_ID_PERE)
 Values
   (247, 'Accueil physique et téléphonique', NULL, NULL, NULL, SYSDATE, SYSDATE, 21);
Insert into GRHUM.FORMATION_PERSONNEL
   (FOR_ID, FOR_LIBELLE, FOR_COMMENTAIRE, FOR_D_OUVERTURE, FOR_D_FERMETURE, 
    D_CREATION, D_MODIFICATION, FOR_ID_PERE)
 Values
   (248, 'La correspondance administrative', NULL, NULL, NULL, SYSDATE, SYSDATE, 21);
Insert into GRHUM.FORMATION_PERSONNEL
   (FOR_ID, FOR_LIBELLE, FOR_COMMENTAIRE, FOR_D_OUVERTURE, FOR_D_FERMETURE, 
    D_CREATION, D_MODIFICATION, FOR_ID_PERE)
 Values
   (249, 'Améliorer ses écrits professionnels', NULL, NULL, NULL, SYSDATE, SYSDATE, 21);
Insert into GRHUM.FORMATION_PERSONNEL
   (FOR_ID, FOR_LIBELLE, FOR_COMMENTAIRE, FOR_D_OUVERTURE, FOR_D_FERMETURE, 
    D_CREATION, D_MODIFICATION, FOR_ID_PERE)
 Values
   (250, 'Role et fonctions du secrétaire assistant', NULL, NULL, NULL, SYSDATE, SYSDATE, 21);
Insert into GRHUM.FORMATION_PERSONNEL
   (FOR_ID, FOR_LIBELLE, FOR_COMMENTAIRE, FOR_D_OUVERTURE, FOR_D_FERMETURE, 
    D_CREATION, D_MODIFICATION, FOR_ID_PERE)
 Values
   (251, 'Techniques d''animation et de pédagogie interactive', NULL, NULL, NULL, SYSDATE, SYSDATE, 21);
Insert into GRHUM.FORMATION_PERSONNEL
   (FOR_ID, FOR_LIBELLE, FOR_COMMENTAIRE, FOR_D_OUVERTURE, FOR_D_FERMETURE, 
    D_CREATION, D_MODIFICATION, FOR_ID_PERE)
 Values
   (252, 'Techniques de compte-rendu, notes de service, notes de synthèse', NULL, NULL, NULL, SYSDATE, SYSDATE, 21);
Insert into GRHUM.FORMATION_PERSONNEL
   (FOR_ID, FOR_LIBELLE, FOR_COMMENTAIRE, FOR_D_OUVERTURE, FOR_D_FERMETURE, 
    D_CREATION, D_MODIFICATION, FOR_ID_PERE)
 Values
   (253, 'LANGAGE XML', NULL, NULL, NULL, SYSDATE, SYSDATE, 29);
Insert into GRHUM.FORMATION_PERSONNEL
   (FOR_ID, FOR_LIBELLE, FOR_COMMENTAIRE, FOR_D_OUVERTURE, FOR_D_FERMETURE, 
    D_CREATION, D_MODIFICATION, FOR_ID_PERE)
 Values
   (254, 'Base de données avancées', NULL, NULL, NULL, SYSDATE, SYSDATE, 29);
Insert into GRHUM.FORMATION_PERSONNEL
   (FOR_ID, FOR_LIBELLE, FOR_COMMENTAIRE, FOR_D_OUVERTURE, FOR_D_FERMETURE, 
    D_CREATION, D_MODIFICATION, FOR_ID_PERE)
 Values
   (255, 'Interfaces WEB avec JAVA', NULL, NULL, NULL, SYSDATE, SYSDATE, 29);
Insert into GRHUM.FORMATION_PERSONNEL
   (FOR_ID, FOR_LIBELLE, FOR_COMMENTAIRE, FOR_D_OUVERTURE, FOR_D_FERMETURE, 
    D_CREATION, D_MODIFICATION, FOR_ID_PERE)
 Values
   (256, 'Initiation au langage JAVA', NULL, NULL, NULL, SYSDATE, SYSDATE, 29);
Insert into GRHUM.FORMATION_PERSONNEL
   (FOR_ID, FOR_LIBELLE, FOR_COMMENTAIRE, FOR_D_OUVERTURE, FOR_D_FERMETURE, 
    D_CREATION, D_MODIFICATION, FOR_ID_PERE)
 Values
   (257, 'Perfectionnement JAVA & XML', NULL, NULL, NULL, SYSDATE, SYSDATE, 29);
Insert into GRHUM.FORMATION_PERSONNEL
   (FOR_ID, FOR_LIBELLE, FOR_COMMENTAIRE, FOR_D_OUVERTURE, FOR_D_FERMETURE, 
    D_CREATION, D_MODIFICATION, FOR_ID_PERE)
 Values
   (258, 'Salle pédagogique sous linux', NULL, NULL, NULL, SYSDATE, SYSDATE, 29);
Insert into GRHUM.FORMATION_PERSONNEL
   (FOR_ID, FOR_LIBELLE, FOR_COMMENTAIRE, FOR_D_OUVERTURE, FOR_D_FERMETURE, 
    D_CREATION, D_MODIFICATION, FOR_ID_PERE)
 Values
   (259, 'Approfondissement du langage JAVA', NULL, NULL, NULL, SYSDATE, SYSDATE, 29);
Insert into GRHUM.FORMATION_PERSONNEL
   (FOR_ID, FOR_LIBELLE, FOR_COMMENTAIRE, FOR_D_OUVERTURE, FOR_D_FERMETURE, 
    D_CREATION, D_MODIFICATION, FOR_ID_PERE)
 Values
   (260, 'LINUX - LES BASES DE L''ADMINISTRATION', NULL, NULL, NULL, SYSDATE, SYSDATE, 29);
Insert into GRHUM.FORMATION_PERSONNEL
   (FOR_ID, FOR_LIBELLE, FOR_COMMENTAIRE, FOR_D_OUVERTURE, FOR_D_FERMETURE, 
    D_CREATION, D_MODIFICATION, FOR_ID_PERE)
 Values
   (261, 'Utilisation d''XML avec le langage JAVA', NULL, NULL, NULL, SYSDATE, SYSDATE, 29);
Insert into GRHUM.FORMATION_PERSONNEL
   (FOR_ID, FOR_LIBELLE, FOR_COMMENTAIRE, FOR_D_OUVERTURE, FOR_D_FERMETURE, 
    D_CREATION, D_MODIFICATION, FOR_ID_PERE)
 Values
   (262, 'LINUX ADMINISTRATION - Perfectionnement', NULL, NULL, NULL, SYSDATE, SYSDATE, 29);
Insert into GRHUM.FORMATION_PERSONNEL
   (FOR_ID, FOR_LIBELLE, FOR_COMMENTAIRE, FOR_D_OUVERTURE, FOR_D_FERMETURE, 
    D_CREATION, D_MODIFICATION, FOR_ID_PERE)
 Values
   (263, 'Utilisation d''XML dans des applications JAVA', NULL, NULL, NULL, SYSDATE, SYSDATE, 29);
Insert into GRHUM.FORMATION_PERSONNEL
   (FOR_ID, FOR_LIBELLE, FOR_COMMENTAIRE, FOR_D_OUVERTURE, FOR_D_FERMETURE, 
    D_CREATION, D_MODIFICATION, FOR_ID_PERE)
 Values
   (264, 'Fonctionnalités avancées de la Bibliothèque JAVA', NULL, NULL, NULL, SYSDATE, SYSDATE, 29);
Insert into GRHUM.FORMATION_PERSONNEL
   (FOR_ID, FOR_LIBELLE, FOR_COMMENTAIRE, FOR_D_OUVERTURE, FOR_D_FERMETURE, 
    D_CREATION, D_MODIFICATION, FOR_ID_PERE)
 Values
   (265, 'Bibliométrie', NULL, NULL, NULL, SYSDATE, SYSDATE, 5);
Insert into GRHUM.FORMATION_PERSONNEL
   (FOR_ID, FOR_LIBELLE, FOR_COMMENTAIRE, FOR_D_OUVERTURE, FOR_D_FERMETURE, 
    D_CREATION, D_MODIFICATION, FOR_ID_PERE)
 Values
   (266, 'Public carcéral', NULL, NULL, NULL, SYSDATE, SYSDATE, 5);
Insert into GRHUM.FORMATION_PERSONNEL
   (FOR_ID, FOR_LIBELLE, FOR_COMMENTAIRE, FOR_D_OUVERTURE, FOR_D_FERMETURE, 
    D_CREATION, D_MODIFICATION, FOR_ID_PERE)
 Values
   (267, 'Indexation RAMEAU', NULL, NULL, NULL, SYSDATE, SYSDATE, 5);
Insert into GRHUM.FORMATION_PERSONNEL
   (FOR_ID, FOR_LIBELLE, FOR_COMMENTAIRE, FOR_D_OUVERTURE, FOR_D_FERMETURE, 
    D_CREATION, D_MODIFICATION, FOR_ID_PERE)
 Values
   (268, 'Accueil au multimédia', NULL, NULL, NULL, SYSDATE, SYSDATE, 5);
Insert into GRHUM.FORMATION_PERSONNEL
   (FOR_ID, FOR_LIBELLE, FOR_COMMENTAIRE, FOR_D_OUVERTURE, FOR_D_FERMETURE, 
    D_CREATION, D_MODIFICATION, FOR_ID_PERE)
 Values
   (269, 'La Gestion des archives', NULL, NULL, NULL, SYSDATE, SYSDATE, 5);
Insert into GRHUM.FORMATION_PERSONNEL
   (FOR_ID, FOR_LIBELLE, FOR_COMMENTAIRE, FOR_D_OUVERTURE, FOR_D_FERMETURE, 
    D_CREATION, D_MODIFICATION, FOR_ID_PERE)
 Values
   (270, 'Initiation au catalogage', NULL, NULL, NULL, SYSDATE, SYSDATE, 5);
Insert into GRHUM.FORMATION_PERSONNEL
   (FOR_ID, FOR_LIBELLE, FOR_COMMENTAIRE, FOR_D_OUVERTURE, FOR_D_FERMETURE, 
    D_CREATION, D_MODIFICATION, FOR_ID_PERE)
 Values
   (271, 'Scopus par formation web', NULL, NULL, NULL, SYSDATE, SYSDATE, 5);
Insert into GRHUM.FORMATION_PERSONNEL
   (FOR_ID, FOR_LIBELLE, FOR_COMMENTAIRE, FOR_D_OUVERTURE, FOR_D_FERMETURE, 
    D_CREATION, D_MODIFICATION, FOR_ID_PERE)
 Values
   (272, 'la recherche documentaire', NULL, NULL, NULL, SYSDATE, SYSDATE, 5);
Insert into GRHUM.FORMATION_PERSONNEL
   (FOR_ID, FOR_LIBELLE, FOR_COMMENTAIRE, FOR_D_OUVERTURE, FOR_D_FERMETURE, 
    D_CREATION, D_MODIFICATION, FOR_ID_PERE)
 Values
   (273, 'Acquisitions en Techniques', NULL, NULL, NULL, SYSDATE, SYSDATE, 5);
Insert into GRHUM.FORMATION_PERSONNEL
   (FOR_ID, FOR_LIBELLE, FOR_COMMENTAIRE, FOR_D_OUVERTURE, FOR_D_FERMETURE, 
    D_CREATION, D_MODIFICATION, FOR_ID_PERE)
 Values
   (274, 'Anglais bibliothéconomique', NULL, NULL, NULL, SYSDATE, SYSDATE, 5);
Insert into GRHUM.FORMATION_PERSONNEL
   (FOR_ID, FOR_LIBELLE, FOR_COMMENTAIRE, FOR_D_OUVERTURE, FOR_D_FERMETURE, 
    D_CREATION, D_MODIFICATION, FOR_ID_PERE)
 Values
   (275, 'Documentation électronique', NULL, NULL, NULL, SYSDATE, SYSDATE, 5);
Insert into GRHUM.FORMATION_PERSONNEL
   (FOR_ID, FOR_LIBELLE, FOR_COMMENTAIRE, FOR_D_OUVERTURE, FOR_D_FERMETURE, 
    D_CREATION, D_MODIFICATION, FOR_ID_PERE)
 Values
   (276, 'Perfectionnement en catalogage', NULL, NULL, NULL, SYSDATE, SYSDATE, 5);
Insert into GRHUM.FORMATION_PERSONNEL
   (FOR_ID, FOR_LIBELLE, FOR_COMMENTAIRE, FOR_D_OUVERTURE, FOR_D_FERMETURE, 
    D_CREATION, D_MODIFICATION, FOR_ID_PERE)
 Values
   (277, 'Recherche documentaire sur Internet', NULL, NULL, NULL, SYSDATE, SYSDATE, 5);
Insert into GRHUM.FORMATION_PERSONNEL
   (FOR_ID, FOR_LIBELLE, FOR_COMMENTAIRE, FOR_D_OUVERTURE, FOR_D_FERMETURE, 
    D_CREATION, D_MODIFICATION, FOR_ID_PERE)
 Values
   (278, 'Formations aux ressources électroniques', NULL, NULL, NULL, SYSDATE, SYSDATE, 5);
Insert into GRHUM.FORMATION_PERSONNEL
   (FOR_ID, FOR_LIBELLE, FOR_COMMENTAIRE, FOR_D_OUVERTURE, FOR_D_FERMETURE, 
    D_CREATION, D_MODIFICATION, FOR_ID_PERE)
 Values
   (279, 'Recherche d''information sur internet, métamoteur', NULL, NULL, NULL, SYSDATE, SYSDATE, 5);
Insert into GRHUM.FORMATION_PERSONNEL
   (FOR_ID, FOR_LIBELLE, FOR_COMMENTAIRE, FOR_D_OUVERTURE, FOR_D_FERMETURE, 
    D_CREATION, D_MODIFICATION, FOR_ID_PERE)
 Values
   (280, 'développement des collections audiovisuelles (BPI)', NULL, NULL, NULL, SYSDATE, SYSDATE, 5);
Insert into GRHUM.FORMATION_PERSONNEL
   (FOR_ID, FOR_LIBELLE, FOR_COMMENTAIRE, FOR_D_OUVERTURE, FOR_D_FERMETURE, 
    D_CREATION, D_MODIFICATION, FOR_ID_PERE)
 Values
   (281, 'Pilotage de l''établissement', NULL, NULL, NULL, SYSDATE, SYSDATE, 16);
Insert into GRHUM.FORMATION_PERSONNEL
   (FOR_ID, FOR_LIBELLE, FOR_COMMENTAIRE, FOR_D_OUVERTURE, FOR_D_FERMETURE, 
    D_CREATION, D_MODIFICATION, FOR_ID_PERE)
 Values
   (282, 'Sociologie des organisations universitaires', NULL, NULL, NULL, SYSDATE, SYSDATE, 16);
Insert into GRHUM.FORMATION_PERSONNEL
   (FOR_ID, FOR_LIBELLE, FOR_COMMENTAIRE, FOR_D_OUVERTURE, FOR_D_FERMETURE, 
    D_CREATION, D_MODIFICATION, FOR_ID_PERE)
 Values
   (283, 'Organisation constitutionnelle et administrative', NULL, NULL, NULL, SYSDATE, SYSDATE, 16);
Insert into GRHUM.FORMATION_PERSONNEL
   (FOR_ID, FOR_LIBELLE, FOR_COMMENTAIRE, FOR_D_OUVERTURE, FOR_D_FERMETURE, 
    D_CREATION, D_MODIFICATION, FOR_ID_PERE)
 Values
   (284, 'Les démarches qualité dans l''enseignement supérieur', NULL, NULL, NULL, SYSDATE, SYSDATE, 16);
Insert into GRHUM.FORMATION_PERSONNEL
   (FOR_ID, FOR_LIBELLE, FOR_COMMENTAIRE, FOR_D_OUVERTURE, FOR_D_FERMETURE, 
    D_CREATION, D_MODIFICATION, FOR_ID_PERE)
 Values
   (285, 'WIN PAIE', NULL, NULL, NULL, SYSDATE, SYSDATE, 17);
Insert into GRHUM.FORMATION_PERSONNEL
   (FOR_ID, FOR_LIBELLE, FOR_COMMENTAIRE, FOR_D_OUVERTURE, FOR_D_FERMETURE, 
    D_CREATION, D_MODIFICATION, FOR_ID_PERE)
 Values
   (286, 'Traitement', NULL, NULL, NULL, SYSDATE, SYSDATE, 17);
Insert into GRHUM.FORMATION_PERSONNEL
   (FOR_ID, FOR_LIBELLE, FOR_COMMENTAIRE, FOR_D_OUVERTURE, FOR_D_FERMETURE, 
    D_CREATION, D_MODIFICATION, FOR_ID_PERE)
 Values
   (287, 'Initiation PAYE', NULL, NULL, NULL, SYSDATE, SYSDATE, 17);
Insert into GRHUM.FORMATION_PERSONNEL
   (FOR_ID, FOR_LIBELLE, FOR_COMMENTAIRE, FOR_D_OUVERTURE, FOR_D_FERMETURE, 
    D_CREATION, D_MODIFICATION, FOR_ID_PERE)
 Values
   (288, 'Tablaaux de bords RH', NULL, NULL, NULL, SYSDATE, SYSDATE, 17);
Insert into GRHUM.FORMATION_PERSONNEL
   (FOR_ID, FOR_LIBELLE, FOR_COMMENTAIRE, FOR_D_OUVERTURE, FOR_D_FERMETURE, 
    D_CREATION, D_MODIFICATION, FOR_ID_PERE)
 Values
   (289, 'Gestion des contractuels', NULL, NULL, NULL, SYSDATE, SYSDATE, 17);
Insert into GRHUM.FORMATION_PERSONNEL
   (FOR_ID, FOR_LIBELLE, FOR_COMMENTAIRE, FOR_D_OUVERTURE, FOR_D_FERMETURE, 
    D_CREATION, D_MODIFICATION, FOR_ID_PERE)
 Values
   (290, 'La réforme des retraites', NULL, NULL, NULL, SYSDATE, SYSDATE, 17);
Insert into GRHUM.FORMATION_PERSONNEL
   (FOR_ID, FOR_LIBELLE, FOR_COMMENTAIRE, FOR_D_OUVERTURE, FOR_D_FERMETURE, 
    D_CREATION, D_MODIFICATION, FOR_ID_PERE)
 Values
   (291, 'Information sur les retraites', NULL, NULL, NULL, SYSDATE, SYSDATE, 17);
Insert into GRHUM.FORMATION_PERSONNEL
   (FOR_ID, FOR_LIBELLE, FOR_COMMENTAIRE, FOR_D_OUVERTURE, FOR_D_FERMETURE, 
    D_CREATION, D_MODIFICATION, FOR_ID_PERE)
 Values
   (292, 'Réglementation assurance chômage', NULL, NULL, NULL, SYSDATE, SYSDATE, 17);
Insert into GRHUM.FORMATION_PERSONNEL
   (FOR_ID, FOR_LIBELLE, FOR_COMMENTAIRE, FOR_D_OUVERTURE, FOR_D_FERMETURE, 
    D_CREATION, D_MODIFICATION, FOR_ID_PERE)
 Values
   (293, 'Initiation au contrôle de gestion', NULL, NULL, NULL, SYSDATE, SYSDATE, 17);
Insert into GRHUM.FORMATION_PERSONNEL
   (FOR_ID, FOR_LIBELLE, FOR_COMMENTAIRE, FOR_D_OUVERTURE, FOR_D_FERMETURE, 
    D_CREATION, D_MODIFICATION, FOR_ID_PERE)
 Values
   (294, 'Déconcentration des actes de gestion', NULL, NULL, NULL, SYSDATE, SYSDATE, 17);
Insert into GRHUM.FORMATION_PERSONNEL
   (FOR_ID, FOR_LIBELLE, FOR_COMMENTAIRE, FOR_D_OUVERTURE, FOR_D_FERMETURE, 
    D_CREATION, D_MODIFICATION, FOR_ID_PERE)
 Values
   (295, 'Entretien professionnel et fiche de poste', NULL, NULL, NULL, SYSDATE, SYSDATE, 17);
Insert into GRHUM.FORMATION_PERSONNEL
   (FOR_ID, FOR_LIBELLE, FOR_COMMENTAIRE, FOR_D_OUVERTURE, FOR_D_FERMETURE, 
    D_CREATION, D_MODIFICATION, FOR_ID_PERE)
 Values
   (296, 'Déroulement de carrière des personnels IATOSS', NULL, NULL, NULL, SYSDATE, SYSDATE, 17);
Insert into GRHUM.FORMATION_PERSONNEL
   (FOR_ID, FOR_LIBELLE, FOR_COMMENTAIRE, FOR_D_OUVERTURE, FOR_D_FERMETURE, 
    D_CREATION, D_MODIFICATION, FOR_ID_PERE)
 Values
   (297, 'Formation aux outils de gestion des concours ITRF', NULL, NULL, NULL, SYSDATE, SYSDATE, 17);
Insert into GRHUM.FORMATION_PERSONNEL
   (FOR_ID, FOR_LIBELLE, FOR_COMMENTAIRE, FOR_D_OUVERTURE, FOR_D_FERMETURE, 
    D_CREATION, D_MODIFICATION, FOR_ID_PERE)
 Values
   (298, 'La V.A.E.  pour la Gestion des ressources humaines', NULL, NULL, NULL, SYSDATE, SYSDATE, 17);
Insert into GRHUM.FORMATION_PERSONNEL
   (FOR_ID, FOR_LIBELLE, FOR_COMMENTAIRE, FOR_D_OUVERTURE, FOR_D_FERMETURE, 
    D_CREATION, D_MODIFICATION, FOR_ID_PERE)
 Values
   (299, 'Congés pour raison de santé dans l''Education Nationale', NULL, NULL, NULL, SYSDATE, SYSDATE, 17);
Insert into GRHUM.FORMATION_PERSONNEL
   (FOR_ID, FOR_LIBELLE, FOR_COMMENTAIRE, FOR_D_OUVERTURE, FOR_D_FERMETURE, 
    D_CREATION, D_MODIFICATION, FOR_ID_PERE)
 Values
   (300, 'Déroulement de carrières des personnels IATOSS/ENSEIGNANTS', NULL, NULL, NULL, SYSDATE, SYSDATE, 17);
Insert into GRHUM.FORMATION_PERSONNEL
   (FOR_ID, FOR_LIBELLE, FOR_COMMENTAIRE, FOR_D_OUVERTURE, FOR_D_FERMETURE, 
    D_CREATION, D_MODIFICATION, FOR_ID_PERE)
 Values
   (301, 'Réforme de la formation professionnelle tout au long de la vie', NULL, NULL, NULL, SYSDATE, SYSDATE, 17);
Insert into GRHUM.FORMATION_PERSONNEL
   (FOR_ID, FOR_LIBELLE, FOR_COMMENTAIRE, FOR_D_OUVERTURE, FOR_D_FERMETURE, 
    D_CREATION, D_MODIFICATION, FOR_ID_PERE)
 Values
   (302, 'Gestion des ressources humaines dans les organisations publiques', NULL, NULL, NULL, SYSDATE, SYSDATE, 17);
Insert into GRHUM.FORMATION_PERSONNEL
   (FOR_ID, FOR_LIBELLE, FOR_COMMENTAIRE, FOR_D_OUVERTURE, FOR_D_FERMETURE, 
    D_CREATION, D_MODIFICATION, FOR_ID_PERE)
 Values
   (303, 'Gestion des chargés d''enseignements et des heures complémentaires', NULL, NULL, NULL, SYSDATE, SYSDATE, 17);
Insert into GRHUM.FORMATION_PERSONNEL
   (FOR_ID, FOR_LIBELLE, FOR_COMMENTAIRE, FOR_D_OUVERTURE, FOR_D_FERMETURE, 
    D_CREATION, D_MODIFICATION, FOR_ID_PERE)
 Values
   (304, 'Formation méthodologique sur l''aide au pilotage dans les établissements', NULL, NULL, NULL, SYSDATE, SYSDATE, 17);
Insert into GRHUM.FORMATION_PERSONNEL
   (FOR_ID, FOR_LIBELLE, FOR_COMMENTAIRE, FOR_D_OUVERTURE, FOR_D_FERMETURE, 
    D_CREATION, D_MODIFICATION, FOR_ID_PERE)
 Values
   (305, 'Finances Publiques', NULL, NULL, NULL, SYSDATE, SYSDATE, 18);
Insert into GRHUM.FORMATION_PERSONNEL
   (FOR_ID, FOR_LIBELLE, FOR_COMMENTAIRE, FOR_D_OUVERTURE, FOR_D_FERMETURE, 
    D_CREATION, D_MODIFICATION, FOR_ID_PERE)
 Values
   (306, 'Formation à la TVA', NULL, NULL, NULL, SYSDATE, SYSDATE, 18);
Insert into GRHUM.FORMATION_PERSONNEL
   (FOR_ID, FOR_LIBELLE, FOR_COMMENTAIRE, FOR_D_OUVERTURE, FOR_D_FERMETURE, 
    D_CREATION, D_MODIFICATION, FOR_ID_PERE)
 Values
   (307, 'Les Marchés Publics', NULL, NULL, NULL, SYSDATE, SYSDATE, 18);
Insert into GRHUM.FORMATION_PERSONNEL
   (FOR_ID, FOR_LIBELLE, FOR_COMMENTAIRE, FOR_D_OUVERTURE, FOR_D_FERMETURE, 
    D_CREATION, D_MODIFICATION, FOR_ID_PERE)
 Values
   (308, 'Comptabilité Générale', NULL, NULL, NULL, SYSDATE, SYSDATE, 18);
Insert into GRHUM.FORMATION_PERSONNEL
   (FOR_ID, FOR_LIBELLE, FOR_COMMENTAIRE, FOR_D_OUVERTURE, FOR_D_FERMETURE, 
    D_CREATION, D_MODIFICATION, FOR_ID_PERE)
 Values
   (309, 'Elaboration d''un budget', NULL, NULL, NULL, SYSDATE, SYSDATE, 18);
Insert into GRHUM.FORMATION_PERSONNEL
   (FOR_ID, FOR_LIBELLE, FOR_COMMENTAIRE, FOR_D_OUVERTURE, FOR_D_FERMETURE, 
    D_CREATION, D_MODIFICATION, FOR_ID_PERE)
 Values
   (310, 'Marchés et services achats', NULL, NULL, NULL, SYSDATE, SYSDATE, 18);
Insert into GRHUM.FORMATION_PERSONNEL
   (FOR_ID, FOR_LIBELLE, FOR_COMMENTAIRE, FOR_D_OUVERTURE, FOR_D_FERMETURE, 
    D_CREATION, D_MODIFICATION, FOR_ID_PERE)
 Values
   (311, 'Actualité des marchés publics', NULL, NULL, NULL, SYSDATE, SYSDATE, 18);
Insert into GRHUM.FORMATION_PERSONNEL
   (FOR_ID, FOR_LIBELLE, FOR_COMMENTAIRE, FOR_D_OUVERTURE, FOR_D_FERMETURE, 
    D_CREATION, D_MODIFICATION, FOR_ID_PERE)
 Values
   (312, 'Formation à la fiscalité directe', NULL, NULL, NULL, SYSDATE, SYSDATE, 18);
Insert into GRHUM.FORMATION_PERSONNEL
   (FOR_ID, FOR_LIBELLE, FOR_COMMENTAIRE, FOR_D_OUVERTURE, FOR_D_FERMETURE, 
    D_CREATION, D_MODIFICATION, FOR_ID_PERE)
 Values
   (313, 'Les opérations de fin d''exercice', NULL, NULL, NULL, SYSDATE, SYSDATE, 18);
Insert into GRHUM.FORMATION_PERSONNEL
   (FOR_ID, FOR_LIBELLE, FOR_COMMENTAIRE, FOR_D_OUVERTURE, FOR_D_FERMETURE, 
    D_CREATION, D_MODIFICATION, FOR_ID_PERE)
 Values
   (314, 'Nouveau code des marchés publics', NULL, NULL, NULL, SYSDATE, SYSDATE, 18);
Insert into GRHUM.FORMATION_PERSONNEL
   (FOR_ID, FOR_LIBELLE, FOR_COMMENTAIRE, FOR_D_OUVERTURE, FOR_D_FERMETURE, 
    D_CREATION, D_MODIFICATION, FOR_ID_PERE)
 Values
   (315, 'Réglementation des marchés publics', NULL, NULL, NULL, SYSDATE, SYSDATE, 18);
Insert into GRHUM.FORMATION_PERSONNEL
   (FOR_ID, FOR_LIBELLE, FOR_COMMENTAIRE, FOR_D_OUVERTURE, FOR_D_FERMETURE, 
    D_CREATION, D_MODIFICATION, FOR_ID_PERE)
 Values
   (316, 'La comptabilité d''exercice dans un EPSCP', NULL, NULL, NULL, SYSDATE, SYSDATE, 18);
Insert into GRHUM.FORMATION_PERSONNEL
   (FOR_ID, FOR_LIBELLE, FOR_COMMENTAIRE, FOR_D_OUVERTURE, FOR_D_FERMETURE, 
    D_CREATION, D_MODIFICATION, FOR_ID_PERE)
 Values
   (317, 'Les modifications du code des marchés publics', NULL, NULL, NULL, SYSDATE, SYSDATE, 18);
Insert into GRHUM.FORMATION_PERSONNEL
   (FOR_ID, FOR_LIBELLE, FOR_COMMENTAIRE, FOR_D_OUVERTURE, FOR_D_FERMETURE, 
    D_CREATION, D_MODIFICATION, FOR_ID_PERE)
 Values
   (318, 'Concevoir et développer sa politique d''achat public', NULL, NULL, NULL, SYSDATE, SYSDATE, 18);
Insert into GRHUM.FORMATION_PERSONNEL
   (FOR_ID, FOR_LIBELLE, FOR_COMMENTAIRE, FOR_D_OUVERTURE, FOR_D_FERMETURE, 
    D_CREATION, D_MODIFICATION, FOR_ID_PERE)
 Values
   (319, 'Formation à la dématérialisation des procédures de marchés publics', NULL, NULL, NULL, SYSDATE, SYSDATE, 18);
Insert into GRHUM.FORMATION_PERSONNEL
   (FOR_ID, FOR_LIBELLE, FOR_COMMENTAIRE, FOR_D_OUVERTURE, FOR_D_FERMETURE, 
    D_CREATION, D_MODIFICATION, FOR_ID_PERE)
 Values
   (320, 'Formation à l''achat public des établissements d''enseignement supérieur', NULL, NULL, NULL, SYSDATE, SYSDATE, 18);
Insert into GRHUM.FORMATION_PERSONNEL
   (FOR_ID, FOR_LIBELLE, FOR_COMMENTAIRE, FOR_D_OUVERTURE, FOR_D_FERMETURE, 
    D_CREATION, D_MODIFICATION, FOR_ID_PERE)
 Values
   (321, 'Business Object', NULL, NULL, NULL, SYSDATE, SYSDATE, 30);
Insert into GRHUM.FORMATION_PERSONNEL
   (FOR_ID, FOR_LIBELLE, FOR_COMMENTAIRE, FOR_D_OUVERTURE, FOR_D_FERMETURE, 
    D_CREATION, D_MODIFICATION, FOR_ID_PERE)
 Values
   (322, 'Prise en main du logiciel Limesurvey et appli CATI', NULL, NULL, NULL, SYSDATE, SYSDATE, 30);
Insert into GRHUM.FORMATION_PERSONNEL
   (FOR_ID, FOR_LIBELLE, FOR_COMMENTAIRE, FOR_D_OUVERTURE, FOR_D_FERMETURE, 
    D_CREATION, D_MODIFICATION, FOR_ID_PERE)
 Values
   (323, 'SPIP - Kit de site web', NULL, NULL, NULL, SYSDATE, SYSDATE, 31);
Insert into GRHUM.FORMATION_PERSONNEL
   (FOR_ID, FOR_LIBELLE, FOR_COMMENTAIRE, FOR_D_OUVERTURE, FOR_D_FERMETURE, 
    D_CREATION, D_MODIFICATION, FOR_ID_PERE)
 Values
   (324, 'Optimisation d''un site WEB ', NULL, NULL, NULL, SYSDATE, SYSDATE, 31);
Insert into GRHUM.FORMATION_PERSONNEL
   (FOR_ID, FOR_LIBELLE, FOR_COMMENTAIRE, FOR_D_OUVERTURE, FOR_D_FERMETURE, 
    D_CREATION, D_MODIFICATION, FOR_ID_PERE)
 Values
   (325, 'Interfaces graphiques avec JAVA', NULL, NULL, NULL, SYSDATE, SYSDATE, 31);
Insert into GRHUM.FORMATION_PERSONNEL
   (FOR_ID, FOR_LIBELLE, FOR_COMMENTAIRE, FOR_D_OUVERTURE, FOR_D_FERMETURE, 
    D_CREATION, D_MODIFICATION, FOR_ID_PERE)
 Values
   (326, 'Système d''Information Documentaire', NULL, NULL, NULL, SYSDATE, SYSDATE, 31);
Insert into GRHUM.FORMATION_PERSONNEL
   (FOR_ID, FOR_LIBELLE, FOR_COMMENTAIRE, FOR_D_OUVERTURE, FOR_D_FERMETURE, 
    D_CREATION, D_MODIFICATION, FOR_ID_PERE)
 Values
   (327, 'Optimisation d''un site Web - Niveau 1', NULL, NULL, NULL, SYSDATE, SYSDATE, 31);
Insert into GRHUM.FORMATION_PERSONNEL
   (FOR_ID, FOR_LIBELLE, FOR_COMMENTAIRE, FOR_D_OUVERTURE, FOR_D_FERMETURE, 
    D_CREATION, D_MODIFICATION, FOR_ID_PERE)
 Values
   (328, 'Utilisation des services INTERNET/INTRANET', NULL, NULL, NULL, SYSDATE, SYSDATE, 31);
Insert into GRHUM.FORMATION_PERSONNEL
   (FOR_ID, FOR_LIBELLE, FOR_COMMENTAIRE, FOR_D_OUVERTURE, FOR_D_FERMETURE, 
    D_CREATION, D_MODIFICATION, FOR_ID_PERE)
 Values
   (329, 'SPIP - KIT laboratoires de recherche - initiation', NULL, NULL, NULL, SYSDATE, SYSDATE, 31);
Insert into GRHUM.FORMATION_PERSONNEL
   (FOR_ID, FOR_LIBELLE, FOR_COMMENTAIRE, FOR_D_OUVERTURE, FOR_D_FERMETURE, 
    D_CREATION, D_MODIFICATION, FOR_ID_PERE)
 Values
   (330, 'SPIP - publication sur le site Web de l''Université', NULL, NULL, NULL, SYSDATE, SYSDATE, 31);
Insert into GRHUM.FORMATION_PERSONNEL
   (FOR_ID, FOR_LIBELLE, FOR_COMMENTAIRE, FOR_D_OUVERTURE, FOR_D_FERMETURE, 
    D_CREATION, D_MODIFICATION, FOR_ID_PERE)
 Values
   (331, 'Technologies de l''information et de la communication', NULL, NULL, NULL, SYSDATE, SYSDATE, 31);
Insert into GRHUM.FORMATION_PERSONNEL
   (FOR_ID, FOR_LIBELLE, FOR_COMMENTAIRE, FOR_D_OUVERTURE, FOR_D_FERMETURE, 
    D_CREATION, D_MODIFICATION, FOR_ID_PERE)
 Values
   (332, 'Publier sur le Web - méthodologie et aspects juridiques', NULL, NULL, NULL, SYSDATE, SYSDATE, 31);
Insert into GRHUM.FORMATION_PERSONNEL
   (FOR_ID, FOR_LIBELLE, FOR_COMMENTAIRE, FOR_D_OUVERTURE, FOR_D_FERMETURE, 
    D_CREATION, D_MODIFICATION, FOR_ID_PERE)
 Values
   (333, 'SPIP - KIT laboratoires de recherche - perfectionnement', NULL, NULL, NULL, SYSDATE, SYSDATE, 31);


DECLARE 
	max_for_id NUMBER;
BEGIN

	SELECT MAX(FOR_ID)+1
	INTO max_for_id 
	FROM GRHUM.FORMATION_PERSONNEL;
    
    IF (max_for_id is NULL) THEN
        max_for_id := 1;
    END IF;
 
	EXECUTE IMMEDIATE 'CREATE SEQUENCE GRHUM.FORMATION_PERSONNEL_SEQ NOCACHE START WITH '||max_for_id ;

END;
/



CREATE OR REPLACE FUNCTION grhum.formation_pers_descendance(
in_for_id NUMBER
)
RETURN CLOB
IS
-- ------------
-- donner la chaine concatenee des libelles de formation de l'ensemble
-- de la descendance d'une formation.
-- ------------

libelle CLOB;
l_libelle VARCHAR2(2000);
 
CURSOR c1 IS 
select for_libelle
from grhum.FORMATION_PERSONNEL
start with for_id = in_for_id
connect by nocycle for_id_pere = prior for_id;

BEGIN

    libelle := '';

    -- si ce n'est pas une feuille, on concatene recursivement ave les enfants    
    OPEN c1();
    LOOP
        FETCH c1 INTO l_libelle;
        EXIT WHEN c1%NOTFOUND;

        libelle := libelle || '|'|| l_libelle;

    END LOOP;
    CLOSE c1;

    RETURN libelle;

END;
/


COMMIT;
