--
-- INDIVIDU_FORMATIONS
--
ALTER TABLE MANGUE.INDIVIDU_FORMATIONS ADD FOR_ID NUMBER;

COMMENT ON COLUMN MANGUE.INDIVIDU_FORMATIONS.FOR_ID IS 'Clef étrangère vers la liste des formations locales de l''établissement.';

ALTER TABLE MANGUE.INDIVIDU_FORMATIONS ADD (
 CONSTRAINT IND_FORMATIONS_REF_FORMATION
FOREIGN KEY (FOR_ID) 
REFERENCES GRHUM.FORMATION_PERSONNEL (FOR_ID));


CREATE TABLE MANGUE.REPART_FORMATION_SOUHAITEE
(
  RFS_KEY                    NUMBER             NOT NULL,
  EVA_KEY                    NUMBER             NOT NULL,
  FOR_ID                     NUMBER,
  RFS_FORMATION_CHAMP_LIBRE  VARCHAR2(4000),
  --RFS_POSITION				 NUMBER				NOT NULL,
  D_CREATION                 DATE               DEFAULT SYSDATE               NOT NULL,
  D_MODIFICATION             DATE               DEFAULT SYSDATE               NOT NULL
)
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
NOMONITORING;

COMMENT ON TABLE MANGUE.REPART_FORMATION_SOUHAITEE IS 'Liste des formations souhaitées lors des entretiens professionnels';

COMMENT ON COLUMN MANGUE.REPART_FORMATION_SOUHAITEE.RFS_KEY IS 'Clé primaire';

COMMENT ON COLUMN MANGUE.REPART_FORMATION_SOUHAITEE.EVA_KEY IS 'Entretien professionnel pendant lequelle la formation a été demandée';

COMMENT ON COLUMN MANGUE.REPART_FORMATION_SOUHAITEE.FOR_ID IS 'Formation demandée (table GRHUM.FORMATION_PERSONNEL)';

COMMENT ON COLUMN MANGUE.REPART_FORMATION_SOUHAITEE.RFS_FORMATION_CHAMP_LIBRE IS 'Formation demandée (champ libre si non trouvée dans GRHUM.FORMATION_PERSONNEL)';

--COMMENT ON COLUMN MANGUE.REPART_FORMATION_SOUHAITEE.RFS_POSITION IS 'Position du souhait (le plus prioritaire est 1)';

COMMENT ON COLUMN MANGUE.REPART_FORMATION_SOUHAITEE.D_CREATION IS 'Date de création de l''enregistrement (interne)';

COMMENT ON COLUMN MANGUE.REPART_FORMATION_SOUHAITEE.D_MODIFICATION IS 'Date de dernière modification de l''enregistrement (interne)';


ALTER TABLE MANGUE.REPART_FORMATION_SOUHAITEE ADD (
  CONSTRAINT PK_REPART_FORMATION_SOUHAITEE
 PRIMARY KEY
 (RFS_KEY),
  CONSTRAINT CHK_RFS_FOR_NON_VIDE
 CHECK ((FOR_ID IS NULL AND RFS_FORMATION_CHAMP_LIBRE IS NOT NULL) OR (FOR_ID IS NOT NULL AND RFS_FORMATION_CHAMP_LIBRE IS NULL)));

ALTER TABLE MANGUE.REPART_FORMATION_SOUHAITEE ADD (
  CONSTRAINT FK_RFS_FORMATION_PERSONNEL FOREIGN KEY (FOR_ID) REFERENCES GRHUM.FORMATION_PERSONNEL (FOR_ID),
  CONSTRAINT FK_RFS_EVALUATION FOREIGN KEY (EVA_KEY) REFERENCES MANGUE.EVALUATION (EVA_KEY));

CREATE SEQUENCE MANGUE.REPART_FORMATION_SOUHAITEE_SEQ NOCACHE;