package org.cocktail.ycrifwk.components;
// Generated by the WOLips TemplateEngine Plug-in at 19 sept. 2005 14:48:37

import org.cocktail.fwkcktlwebapp.server.components.CktlWebComponent;

import com.webobjects.appserver.WOContext;

public class YPanelAvertissement extends CktlWebComponent {

  public YPanelAvertissement(WOContext context) {
    super(context);
  }

}