package org.cocktail.feve.components.common;
// Generated by the WOLips TemplateEngine Plug-in at 30 ao�t 2005 11:47:51

import org.cocktail.feve.eos.modele.grhum.EOReferensCompetences;

import com.webobjects.appserver.WOContext;


public class CompCompetenceDisplay extends FeveWebComponent {

  public EOReferensCompetences laCompetence;
  
    public CompCompetenceDisplay(WOContext context) {
        super(context);
    }

}